### ISSUE TITLE
__cplusplus support into flux header files

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#1199]
This was diiscussed as part of #1198. Having this support will make flux header files safer to be used in C++ code.

**Comment by garlick** [comment]
@morone commented in #1198: 
> I went through and made the change to all the C headers in flux core. Unfortunately, our python interface auto-generator threw a fit when it hit those statements. It seemed like it wasn't properly preprocessing the files and things were still in its file that should have been removed at preprocessing time.

**Comment by garlick** [comment]
Just to get the actual errors into the bug, I tried this:
```diff
diff --git a/src/common/libflux/message.h b/src/common/libflux/message.h
index 9400935..27adf56 100644
--- a/src/common/libflux/message.h
+++ b/src/common/libflux/message.h
@@ -1,6 +1,10 @@
 #ifndef _FLUX_CORE_MESSAGE_H
 #define _FLUX_CORE_MESSAGE_H
 
+#ifdef __cplusplus
+extern "C" {
+#endif
+
 #include <stdbool.h>
 #include <stdint.h>
 #include <stdarg.h>
@@ -307,6 +311,10 @@ int flux_msg_get_route_count (const flux_msg_t *msg);
  */
 char *flux_msg_get_route_string (const flux_msg_t *msg);
 
+#ifdef __cplusplus
+}
+#endif
+
 #endif /* !_FLUX_CORE_MESSAGE_H */
 
 /*
```
which resulted in this:
```
Making all in flux
make[1]: Entering directory '/home/garlick/proj/flux-core/src/bindings/python/flux'
Making all in core
make[2]: Entering directory '/home/garlick/proj/flux-core/src/bindings/python/flux/core'
echo Copying core libraries to where they can be used by python out of tree
Copying core libraries to where they can be used by python out of tree
[ "../../../../.." != "../../../../.." ] && cp  ../../../../../src/bindings/python/flux/core/*.py ./ || true
make[2]: Leaving directory '/home/garlick/proj/flux-core/src/bindings/python/flux/core'
make[2]: Entering directory '/home/garlick/proj/flux-core/src/bindings/python/flux'
/usr/bin/python ../../../../src/bindings/python/make_binding.py --path ../../../../src/common/libflux \
  			  --package flux \
                          --modname _core \
			  --add_sub '.*va_list.*|||' \
			  --ignore_header 'handle_impl' \
			  --ignore_header 'macros' \
			  --add_long_sub 'FLUX_SEC_TYPE_ALL.*\n.*\),|||FLUX_SEC_TYPE_ALL = 7,'\
			  flux.h
/usr/bin/python _core_build.py
Traceback (most recent call last):
  File "_core_build.py", line 1094, in <module>
    """)
  File "/usr/lib/python2.7/dist-packages/cffi/api.py", line 105, in cdef
    self._cdef(csource, override=override, packed=packed)
  File "/usr/lib/python2.7/dist-packages/cffi/api.py", line 119, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/usr/lib/python2.7/dist-packages/cffi/cparser.py", line 289, in parse
    self._internal_parse(csource)
  File "/usr/lib/python2.7/dist-packages/cffi/cparser.py", line 294, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/usr/lib/python2.7/dist-packages/cffi/cparser.py", line 252, in _parse
    self.convert_pycparser_error(e, csource)
  File "/usr/lib/python2.7/dist-packages/cffi/cparser.py", line 281, in convert_pycparser_error
    raise api.CDefError(msg)
cffi.api.CDefError: cannot parse "extern "C" {"
:24:8: before: "C"
Makefile:1013: recipe for target '_core.c' failed
make[2]: *** [_core.c] Error 1
make[2]: Leaving directory '/home/garlick/proj/flux-core/src/bindings/python/flux'
Makefile:733: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/garlick/proj/flux-core/src/bindings/python/flux'
Makefile:461: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```
