### ISSUE TITLE
broker shutdown hangs in heartbeat

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1312]
When running my hierarchical scheduling tests, I occasionally get an instance that doesn't cleanly shutdown when the initial program exits.  It appears that the hang is caused by a heartbeat send that never completes. I'm running the tests under flux-core 0.6.0, so this might not be relevant anymore.

Exact `flux_send` that is hanging: https://github.com/flux-framework/flux-core/blob/v0.6.0/src/broker/heartbeat.c#L141

Backtrace from GDB:
```
(gdb) bt
#0  0x00002aaaac4a2a3d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00002aaaab85d9aa in zmq::signaler_t::wait(int) () from /usr/lib64/libzmq.so.5
#2  0x00002aaaab8426b0 in zmq::mailbox_t::recv(zmq::command_t*, int) () from /usr/lib64/libzmq.so.5
#3  0x00002aaaab85eb6a in zmq::socket_base_t::process_commands(int, bool) () from /usr/lib64/libzmq.so.5
#4  0x00002aaaab85ef6f in zmq::socket_base_t::send(zmq::msg_t*, int) () from /usr/lib64/libzmq.so.5
#5  0x00002aaaab87596c in s_sendmsg(zmq::socket_base_t*, zmq_msg_t*, int) () from /usr/lib64/libzmq.so.5
#6  0x00002aaaab597208 in zframe_send () from /usr/lib64/libczmq.so.3
#7  0x00002aaaaaf23392 in flux_msg_sendzsock (sock=<optimized out>, msg=msg@entry=0x68fb10) at message.c:1308
#8  0x000000000040cbb7 in module_sendmsg (p=p@entry=0x688720, msg=msg@entry=0x68fb10) at module.c:269
#9  0x000000000040daa9 in module_event_mcast (mh=0x647c60, msg=0x68fb10) at module.c:769
#10 0x0000000000409013 in handle_event (ctx=ctx@entry=0x7fffffff9b40, zmsg=zmsg@entry=0x7fffffff9938) at broker.c:2541
#11 0x0000000000409289 in broker_event_sendmsg (ctx=ctx@entry=0x7fffffff9b40, zmsg=zmsg@entry=0x7fffffff9938) at broker.c:2868
#12 0x000000000040a194 in broker_send (impl=0x7fffffff9b40, msg=0x6e88c0, flags=<optimized out>) at broker.c:2902
#13 0x00002aaaaaf1bb14 in flux_send (h=0x650470, msg=msg@entry=0x6e88c0, flags=flags@entry=0) at handle.c:584
#14 0x000000000040f7bd in timer_cb (r=<optimized out>, w=<optimized out>, revents=<optimized out>, arg=0x64a820) at heartbeat.c:141
#15 0x00002aaaaaf37f75 in ev_invoke_pending (loop=0x2aaaab15d4e0 <default_loop_struct>) at ev.c:3088
#16 0x00002aaaaaf3b0d7 in ev_run (loop=0x2aaaab15d4e0 <default_loop_struct>, flags=0) at ev.c:3488
#17 0x00002aaaaaf1d2ed in flux_reactor_run (r=0x64c8b0, flags=flags@entry=0) at reactor.c:134
#18 0x0000000000407feb in main (argc=<optimized out>, argv=<optimized out>) at broker.c:659
```

**Comment by garlick** [comment]
I _think_ this can no longer happen.
