### ISSUE TITLE
SIGTERM cmbd other than rank 0 causes assertion failure

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#132]
SLURM job timeout sent SIGTERM to cmbd other than rank 0 which resulted in an assertion failure in `cmb_event_sendmsg`:

```
cmbd: cmbd.c:1569: cmb_event_sendmsg: Assertion `ctx->rank == 0' failed.
```

Stack trace:

```
(gdb) bt
#0  0x00002aaaab9d8625 in raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00002aaaab9d9e05 in abort () at abort.c:92
#2  0x00002aaaab9d174e in __assert_fail_base (fmt=<value optimized out>,  assertion=0x41c1a7 "ctx->rank == 0", file=0x41c0fa "cmbd.c",  line=<value optimized out>, function=<value optimized out>) at assert.c:96
#3  0x00002aaaab9d1810 in __assert_fail (assertion=0x41c1a7 "ctx->rank == 0",  file=0x41c0fa "cmbd.c", line=1569, function=0x41d5e0 "cmb_event_sendmsg") at assert.c:105
#4  0x0000000000406220 in cmb_event_sendmsg (ctx=0x7fffffffd4e0,  o=<value optimized out>, topic=0x41c138 "shutdown") at cmbd.c:1569
#5  cmb_event_send (ctx=0x7fffffffd4e0, o=<value optimized out>,  topic=0x41c138 "shutdown") at cmbd.c:1626
#6  0x000000000040a3c6 in shutdown_send (ctx=0x7fffffffd4e0, grace=2, rc=0,  fmt=<value optimized out>) at cmbd.c:1545
#7  0x000000000040a4a0 in signal_cb (zl=<value optimized out>,  item=<value optimized out>, ctx=0x7fffffffd4e0) at cmbd.c:2107
#8  0x00002aaaab355e54 in zloop_start () from /usr/lib64/libczmq.so.1
#9  0x00000000004097f0 in main (argc=<value optimized out>,  argv=<value optimized out>) at cmbd.c:555

```

This seems pretty straightforward, but the only thing I'm not sure about is why only rank 0 is allowed to send events. If that is the case, should all ranks except 0 ignore `SIGTERM` `SIGINT` etc? Or should they forward shutdown as message to rank 0 which then generates an event?
(Sorry feel like I should know how events are supposed to work better)

Seems like "send a signal to terminate distributed process" probably needs more thought.

Oh, and this reproducer works:

```
 grondo@ipa15:~/git/flux-core.git$ src/cmd/flux start --size=2 'killall cmbd-1'
cmbd: 147073-0: starting shell
cmbd: cmbd.c:1569: cmb_event_sendmsg: Assertion `ctx->rank == 0' failed.
cmbd: 0: shutdown in 2s: Exited
flux-start: 1 (pid 147075) Aborted
flux-start: 0 (pid 147074) Killed
```

A good entry to the testsuite would probably be to send signals to various cmbd's and ensure they behave "properly", however that is.

**Comment by grondo** [comment]
Ah, sorry I didn't notice the existing issue.

**Comment by garlick** [comment]
I tried essentially the same thing as the reproducer, e.g.
```
$ flux start --size=2
$ ps -fe|grep broker
...
$ kill 34421
$
```
No assertion failure.  Closing.
