### ISSUE TITLE
occasional sigabort in cmb.exec on exec failure

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1638]
We're seeing an occasional SIGABRT from the forked child of a cmb.exec on exec failure, e.g. EPERM or EEXIST. This causes a failure in the exec tests with the incorrect return code.

The problem is most likely due to the use of `exit(3)` in the current libsubprocess on exec failure. Use of `_exit` instead may help, as it appears the abort() comes from the copy of libzmq running in the forked process' address space...

@chu11 -- same principle will apply to your new libsubprocess -- though you may have already anticipated and fixed this issue.

```
[91mFound corefile for /tmp/flux/libexec/flux/cmd/flux-broker[39m

warning: core file may not match specified executable file.
[New LWP 4198]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/tmp/flux/libexec/flux/cmd/flux-broker --setattr=broker.rundir=/tmp/flux-4066-2'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00002b61233f1c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.

Thread 1 (Thread 0x2b6122218800 (LWP 4198)):
#0  0x00002b61233f1c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 4198
        selftid = 4198
#1  0x00002b61233f5028 in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x1eb4940, sa_sigaction = 0x1eb4940}, sa_mask = {__val = {32119952, 31975648, 47696184268279, 5, 0, 5, 47696202964272, 47696204511303, 31975648, 379, 47696184296869, 4294967295, 18446744073709551456, 47696206887376, 4294967295, 47696204511303}}, sa_flags = 572622848, sa_restorer = 0xb1}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00002b6122b370fc in zmq::zmq_abort (errmsg_=errmsg_@entry=0x2b612353b847 "Bad file descriptor") at src/err.cpp:84
No locals.
#3  0x00002b6122b60494 in zmq::signaler_t::send (this=<optimized out>) at src/signaler.cpp:177
        errstr = 0x2b612353b847 "Bad file descriptor"
        inc = 1
        sz = <optimized out>
#4  0x00002b6122b4bee0 in zmq::mailbox_t::send (this=<optimized out>, cmd_=...) at src/mailbox.cpp:65
        ok = false
#5  0x00002b6122b39d75 in zmq::ctx_t::send_command (this=<optimized out>, tid_=<optimized out>, command_=...) at src/ctx.cpp:373
No locals.
#6  0x00002b6122b52825 in send_command (cmd_=..., this=0x1e7e8e0) at src/object.cpp:435
No locals.
#7  zmq::object_t::send_reap (this=this@entry=0x1e7e8e0, socket_=socket_@entry=0x1e7e8e0) at src/object.cpp:326
        cmd = {destination = 0x1e7e0f0, type = zmq::command_t::reap, args = {stop = {<No data fields>}, plug = {<No data fields>}, own = {object = 0x1e7e8e0}, attach = {engine = 0x1e7e8e0}, bind = {pipe = 0x1e7e8e0}, activate_read = {<No data fields>}, activate_write = {msgs_read = 31975648}, hiccup = {pipe = 0x1e7e8e0}, pipe_term = {<No data fields>}, pipe_term_ack = {<No data fields>}, term_req = {object = 0x1e7e8e0}, term = {linger = 31975648}, term_ack = {<No data fields>}, reap = {socket = 0x1e7e8e0}, reaped = {<No data fields>}, done = {<No data fields>}}}
#8  0x00002b6122b61796 in zmq::socket_base_t::close (this=this@entry=0x1e7e8e0) at src/socket_base.cpp:953
No locals.
#9  0x00002b6122b7754a in zmq_close (s_=0x1e7e8e0) at src/zmq.cpp:260
No locals.
#10 0x00002b61228c1a60 in zsys_shutdown () at src/zsys.c:239
        busy = <optimized out>
        sockref = 0x1e7efb0
#11 0x00002b61233f71a9 in __run_exit_handlers (status=status@entry=127, listp=0x2b612377d6c8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
        atfct = <optimized out>
        onfct = <optimized out>
        cxafct = <optimized out>
        f = <optimized out>
#12 0x00002b61233f71f5 in __GI_exit (status=status@entry=127) at exit.c:104
No locals.
#13 0x000000000041f264 in subprocess_child (p=0x1e91950) at subprocess.c:812
        errnum = 2
        code = 127
        argv = <optimized out>
#14 subprocess_fork (p=p@entry=0x1e91950) at subprocess.c:875
No locals.
#15 0x0000000000413cb7 in exec_request_cb (h=0x1e79b90, mh=<optimized out>, msg=0x1eb4940, arg=0x1ea1c90) at exec.c:367
        x = 0x1ea1c90
        args = 0x1eb6fc0
        env = 0x1e79b00
        cwd = 0x1eb70c0 "/home/travis/build/grondo/flux-core/t/trash-directory.t0005-exec"
        p = 0x1e91950
        __FUNCTION__ = "exec_request_cb"
#16 0x00002b612241f0c4 in call_handler (mh=mh@entry=0x1ea1cf0, msg=msg@entry=0x1eb4940) at msg_handler.c:302
        rolemask = 1
        matchtag = 0
#17 0x00002b612241f23f in dispatch_message (type=1, msg=0x1eb4940, d=0x1e7aa60) at msg_handler.c:326
        mh = 0x1ea1cf0
        match = false
#18 handle_cb (r=0x1e797b0, hw=<optimized out>, revents=<optimized out>, arg=0x1e7aa60) at msg_handler.c:392
        d = 0x1e7aa60
        msg = 0x1eb4940
        rc = -1
        type = 1
        topic = 0x1e90da4 "cmb.exec"
        __FUNCTION__ = "handle_cb"
#19 0x00002b6122447165 in ev_invoke_pending (loop=0x2b6122674ee0 <default_loop_struct>) at ev.c:3314
        p = <optimized out>
#20 0x00002b612244a327 in ev_run (loop=0x2b6122674ee0 <default_loop_struct>, flags=0) at ev.c:3717
        __PRETTY_FUNCTION__ = "ev_run"
#21 0x00002b612241e2d3 in flux_reactor_run (r=0x1e797b0, flags=flags@entry=0) at reactor.c:132
        ev_flags = 0
        count = <optimized out>
#22 0x000000000040804d in main (argc=<optimized out>, argv=<optimized out>) at broker.c:661
        ctx = {sec = 0x1e7a9e0, h = 0x1e79b90, reactor = 0x1e797b0, overlay = 0x1e75d70, attrs = 0x1e76860, userid = 2000, rolemask = 1, modhash = 0x1e74c60, verbose = false, event_recv_seq = 0, event_active = false, services = 0x1e754f0, heartbeat = 0x1e766e0, shutdown = 0x1e76710, shutdown_grace = 1, subscriptions = 0x1e770e0, cache = 0x1e77120, publisher = 0x1e77b70, tbon_k = 2, hello = 0x1e76690, enclosing_h = 0x0, runlevel = 0x1e77a40, sm = 0x1e784b0, init_shell_cmd = 0x1e78a10 "sh ./t0005-exec.t  --logfile", init_shell_cmd_len = 29}
        sigwatchers = 0x1e74c20
        sec_typemask = 6
        old_sigmask = {__val = {0, 15, 47696184436304, 47696184248502, 8, 140728501554336, 47696202951984, 140728501554608, 47696203002024, 7491161, 140728501554592, 1928641016, 0, 47696184441032, 47696184427752, 47696214863761}}
        old_sigact_int = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 1, 0, 4390196, 47696198611792, 31950000, 31942752, 140728501554960, 47696184296869, 0, 47696203161312, 140728501554640, 0, 2, 255, 2}}, sa_flags = 0, sa_restorer = 0x0}
        old_sigact_term = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 1, 0, 4390196, 47696198611792, 31950000, 31942752, 140728501554960, 47696184296869, 0, 47696203161312, 140728501554640, 0, 2, 255, 2}}, sa_flags = 0, sa_restorer = 0x0}
        boot_method = 0x42e00f "pmi"
        __FUNCTION__ = "main"
        sigmask = {__val = {18446744067267100671, 18446744073709551615 <repeats 15 times>}}
        keydir = 0x1e78320 "/home/travis/.flux"
        rank = 0
        size = <optimized out>
        __PRETTY_FUNCTION__ = "main"
```

**Comment by chu11** [comment]
comment on your patch (although it's not submitted in a PR yet).  Should it be all calls to ```exit()``` within ```subprocess_child()```.  Not just the one after the failed ```exec()```?  To me, it should be all ```exit()``` calls.

**Comment by grondo** [comment]
Yes, it should be all calls. Sorry, I was just trying to get my branch to pass travis and had to fix the error from exec(2) case only. (All this code will be replaced anyway)
