### ISSUE TITLE
[asan] test_optparse leaks

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1724]
```
=================================================================
==24955==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 104 byte(s) in 1 object(s) allocated from:
    #0 0x7fab07e7ced0 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe8ed0)
    #1 0x55a8d5eae82c in optparse_create ../../../../src/common/liboptparse/optparse.c:676
    #2 0x55a8d5ea6127 in test_optional_argument ../../../../src/common/liboptparse/test/optparse.c:606
    #3 0x55a8d5ea16be in main ../../../../src/common/liboptparse/test/optparse.c:1116
    #4 0x7fab0773bb16 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x22b16)

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7fab07e7d0b8 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe90b8)
    #1 0x7fab07b4ed72 in zlist_new (/usr/lib/x86_64-linux-gnu/libczmq.so.4+0x28d72)
    #2 0x55a8d5eb198c in optparse_reset ../../../../src/common/liboptparse/optparse.c:1418
    #3 0x55a8d5ea8bd1 in test_non_option_arguments ../../../../src/common/liboptparse/test/optparse.c:1053
    #4 0x55a8d5ea16cd in main ../../../../src/common/liboptparse/test/optparse.c:1119
    #5 0x7fab0773bb16 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x22b16)

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7fab07e7d0b8 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe90b8)
    #1 0x7fab07b4ed72 in zlist_new (/usr/lib/x86_64-linux-gnu/libczmq.so.4+0x28d72)
    #2 0x55a8d5eb198c in optparse_reset ../../../../src/common/liboptparse/optparse.c:1418
    #3 0x55a8d5ea865c in test_reset ../../../../src/common/liboptparse/test/optparse.c:1009
    #4 0x55a8d5ea16c8 in main ../../../../src/common/liboptparse/test/optparse.c:1118
    #5 0x7fab0773bb16 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x22b16)

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7fab07e7d0b8 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe90b8)
    #1 0x7fab07b4ed72 in zlist_new (/usr/lib/x86_64-linux-gnu/libczmq.so.4+0x28d72)
    #2 0x55a8d5eb198c in optparse_reset ../../../../src/common/liboptparse/optparse.c:1418
    #3 0x55a8d5ea8e31 in test_non_option_arguments ../../../../src/common/liboptparse/test/optparse.c:1087
    #4 0x55a8d5ea16cd in main ../../../../src/common/liboptparse/test/optparse.c:1119
    #5 0x7fab0773bb16 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x22b16)

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7fab07e7d0b8 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe90b8)
    #1 0x7fab07b4ed72 in zlist_new (/usr/lib/x86_64-linux-gnu/libczmq.so.4+0x28d72)
    #2 0x55a8d5eb198c in optparse_reset ../../../../src/common/liboptparse/optparse.c:1418
    #3 0x55a8d5ea8cc9 in test_non_option_arguments ../../../../src/common/liboptparse/test/optparse.c:1075
    #4 0x55a8d5ea16cd in main ../../../../src/common/liboptparse/test/optparse.c:1119
    #5 0x7fab0773bb16 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x22b16)

Indirect leak of 4080 byte(s) in 2 object(s) allocated from:
    #0 0x7fab07e7d0b8 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe90b8)
    #1 0x7fab07b4969e in zhash_new (/usr/lib/x86_64-linux-gnu/libczmq.so.4+0x2369e)
    #2 0x55a8d5ea6127 in test_optional_argument ../../../../src/common/liboptparse/test/optparse.c:606
    #3 0x55a8d5ea16be in main ../../../../src/common/liboptparse/test/optparse.c:1116
    #4 0x7fab0773bb16 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x22b16)

Indirect leak of 176 byte(s) in 2 object(s) allocated from:
    #0 0x7fab07e7d0b8 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe90b8)
    #1 0x7fab07b4967f in zhash_new (/usr/lib/x86_64-linux-gnu/libczmq.so.4+0x2367f)
    #2 0x55a8d5ea6127 in test_optional_argument ../../../../src/common/liboptparse/test/optparse.c:606
    #3 0x55a8d5ea16be in main ../../../../src/common/liboptparse/test/optparse.c:1116
    #4 0x7fab0773bb16 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x22b16)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fab07e7d0b8 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe90b8)
    #1 0x7fab07b4ef71 in zlist_append (/usr/lib/x86_64-linux-gnu/libczmq.so.4+0x28f71)

Indirect leak of 7 byte(s) in 1 object(s) allocated from:
    #0 0x7fab07dce7e0 in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x3a7e0)
    #1 0x55a8d5eae850 in optparse_create ../../../../src/common/liboptparse/optparse.c:682
    #2 0x55a8d5ea6127 in test_optional_argument ../../../../src/common/liboptparse/test/optparse.c:606
    #3 0x55a8d5ea16be in main ../../../../src/common/liboptparse/test/optparse.c:1116
    #4 0x7fab0773bb16 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x22b16)

Indirect leak of 7 byte(s) in 1 object(s) allocated from:
    #0 0x7fab07dce7e0 in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x3a7e0)
    #1 0x55a8d5eab9a1 in optparse_fullname ../../../../src/common/liboptparse/optparse.c:296
    #2 0x55a8d5eb088e in optparse_parse_args ../../../../src/common/liboptparse/optparse.c:1271
    #3 0x55a8d5ea63fe in test_optional_argument ../../../../src/common/liboptparse/test/optparse.c:624
    #4 0x55a8d5ea16be in main ../../../../src/common/liboptparse/test/optparse.c:1116
    #5 0x7fab0773bb16 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x22b16)

Indirect leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x7fab07dce7e0 in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x3a7e0)
    #1 0x7fab07b4efb7 in zlist_append (/usr/lib/x86_64-linux-gnu/libczmq.so.4+0x28fb7)

SUMMARY: AddressSanitizer: 4594 byte(s) leaked in 13 allocation(s).
ok 202 - got -b
PASS: test_optparse.t 202 - got -b
ERROR: test_optparse.t - too few tests run (expected 251, got 202)

```

**Comment by SteVwonder** [comment]
I have what I believe to be a fix to these leaks over at https://github.com/stevwonder/flux-core/tree/fix-optparse-asan.  Once I get asan working locally and confirm they are indeed fixed, I'll submit a PR.

**Comment by trws** [comment]
Sounds great! Thanks stephen. In case it becomes relevant, I was testing with asan in GCC 7+, possibly 8, for leaks it’s unlikely to matter but the other ones sometimes differ.

On 12 Oct 2018, at 12:41, Stephen Herbein wrote:

I have what I believe to be a fix to these leaks over at https://github.com/stevwonder/flux-core/tree/fix-optparse-asan. Once I get asan working locally and confirm they are indeed fixed, I'll submit a PR.
