### ISSUE TITLE
[asan] test_cache leaks

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1729]
```
=================================================================
==29911==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 37 byte(s) in 1 object(s) allocated from:
    #0 0x7f3bb5ac2ed0 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe8ed0)
    #1 0x7f3bb544acc4  (/usr/lib/x86_64-linux-gnu/libjansson.so.4+0x5cc4)

Direct leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0x7f3bb5a147e0 in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x3a7e0)
    #1 0x56412cc531e1 in cache_entry_raw_tests ../../../../src/modules/kvs/test/cache.c:116
    #2 0x56412cc52750 in main ../../../../src/modules/kvs/test/cache.c:565
    #3 0x7f3bb4dbfb16 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x22b16)

Indirect leak of 158 byte(s) in 3 object(s) allocated from:
    #0 0x7f3bb5ac2ed0 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe8ed0)
    #1 0x7f3bb5448cb8  (/usr/lib/x86_64-linux-gnu/libjansson.so.4+0x3cb8)

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f3bb5ac2ed0 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe8ed0)
    #1 0x7f3bb5448a4c  (/usr/lib/x86_64-linux-gnu/libjansson.so.4+0x3a4c)
    #2 0x7ffd5f59ae5f  ([stack]+0x1ee5f)

Indirect leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x7f3bb5ac2ed0 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe8ed0)
    #1 0x7f3bb544dc0a in json_object (/usr/lib/x86_64-linux-gnu/libjansson.so.4+0x8c0a)
    #2 0x7ffd5f59ae5f  ([stack]+0x1ee5f)

Indirect leak of 64 byte(s) in 2 object(s) allocated from:
    #0 0x7f3bb5ac2ed0 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe8ed0)
    #1 0x7f3bb544dbde  (/usr/lib/x86_64-linux-gnu/libjansson.so.4+0x8bde)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f3bb5ac2ed0 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe8ed0)
    #1 0x7f3bb544e38d in json_integer (/usr/lib/x86_64-linux-gnu/libjansson.so.4+0x938d)
    #2 0x7ffd5f59ae5f  ([stack]+0x1ee5f)

Indirect leak of 9 byte(s) in 2 object(s) allocated from:
    #0 0x7f3bb5ac2ed0 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe8ed0)
    #1 0x7f3bb544acc4  (/usr/lib/x86_64-linux-gnu/libjansson.so.4+0x5cc4)

SUMMARY: AddressSanitizer: 497 byte(s) leaked in 12 allocation(s).
ok 90 - cache_create works
PASS: test_cache.t 90 - cache_create works
ERROR: test_cache.t - missing test plan
```

**Comment by chu11** [comment]
```
#1 0x56412cc531e1 in cache_entry_raw_tests ../../../../src/modules/kvs/test/cache.c:116
```

this one looks like it could be a real leak, should have been destroyed on a cache entry destroy.

**Comment by chu11** [comment]
Nah, I somewhat aggressively began self-assigning many of the asan issues to myself, then realized I should probably pick em off at a more reasonable pace.  Feel free to pick off any you wish.
