### ISSUE TITLE
FAIL: python/t0009-security.py 1 __main__.TestKVS.test_00_sign_none

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1738]
I'm getting this failure on my desktop when building `--with-flux-security` against `flux-security` master installed in /usr/local:
```
2018-10-15T20:17:26.624726Z broker.err[0]: Run level 2 Exited with non-zero status (rc=1) 0.1s
flux-start: 0 (pid 40342) exited with rc=1
TAP version 13
not ok 1 __main__.TestKVS.test_00_sign_none
FAIL: python/t0009-security.py 1 __main__.TestKVS.test_00_sign_none
  ---
    message: |
      Traceback (most recent call last):
        File "./python/t0009-security.py", line 31, in test_00_sign_none
          unwrapped_payload, wrapping_user = self.context.sign_unwrap(signed_str)
        File "/home/garlick/proj/flux-core/src/bindings/python/flux/security.py", line 71, in sign_unwrap
          output_payload = ffi.unpack(output_payload, output_payload_len)
      AttributeError: 'CompiledFFI' object has no attribute 'unpack'
  ...
ok 2 __main__.TestKVS.test_01_security_error
PASS: python/t0009-security.py 2 __main__.TestKVS.test_01_security_error
1..2
```

I guess the`TestKVS.test` reference is a cut-and-paste-o?

The missing unwrap method is puzzling though...

**Comment by SteVwonder** [comment]
`unpack` was added to cffi in v1.6.  I think we only check that `cffi > 1.1` in `configure.ac`.  Maybe that needs to be bumped up. 

What do you get if you run `python -c "import cffi; print(cffi.__version__)"` on your desktop?

**Comment by SteVwonder** [comment]
@garlick: if you need them immediately, I pushed some fixes to https://github.com/stevwonder/flux-core/tree/py-init-prog
