### ISSUE TITLE
pymod: OverflowError: integer 3046323504 does not fit '32-bit int'

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1801]
My test vm is a 32-bit Ubuntu 18.04 LTS system.  After pr #1757 was merged, I seem to have a new problem with the pymod test:
```
 ./t9001-pymod.t --verbose
expecting success: 
	flux module load pymod --verbose --path=$pymodpath echo

Traceback (most recent call last):
  File "/home/garlick/proj/flux-core/src/bindings/python/flux/core/trampoline.py", line 9, in mod_main_trampoline
    flux_instance = Flux(handle=lib.unpack_long(int_handle))
OverflowError: integer 3046323504 does not fit '32-bit int'
ok 1 - load pymod with echo.py

expecting success: 
	cat <<-EOF | flux python -
	import flux,sys
	p = { "data": "foo" }
	f = flux.Flux()
	r = f.rpc_send ("echo.foo", p)
	sys.exit (not all(item in r.items() for item in p.items()))
EOF

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/garlick/proj/flux-core/src/bindings/python/flux/core/handle.py", line 75, in rpc_send
    return rpc.get()
  File "/home/garlick/proj/flux-core/src/bindings/python/flux/rpc.py", line 61, in get
    resp_str = self.get_str()
  File "/home/garlick/proj/flux-core/src/bindings/python/flux/util.py", line 26, in func_wrapper
    six.reraise(*exception_tuple)
  File "/home/garlick/proj/flux-core/src/bindings/python/flux/util.py", line 16, in func_wrapper
    return func(calling_obj, *args, **kwargs)
  File "/home/garlick/proj/flux-core/src/bindings/python/flux/rpc.py", line 55, in get_str
    self.pimpl.get(j_str)
  File "/home/garlick/proj/flux-core/src/bindings/python/flux/wrapper.py", line 194, in __call__
    raise EnvironmentError(err, os.strerror(err))
EnvironmentError: [Errno 38] Function not implemented
not ok 2 - pymod echo.py function works
#	
#		cat <<-EOF | flux python -
#		import flux,sys
#		p = { "data": "foo" }
#		f = flux.Flux()
#		r = f.rpc_send ("echo.foo", p)
#		sys.exit (not all(item in r.items() for item in p.items()))
#	EOF
#	

expecting success: 
	flux module remove pymod

flux-module: cmb.rmmod[0] pymod: No such file or directory
ok 3 - unload pymod

# failed 1 among 3 test(s)
1..3
2018-11-05T03:13:28.975881Z broker.err[0]: Run level 2 Exited with non-zero status (rc=1) 0.3s
flux-start: 0 (pid 1413) exited with rc=1
```

**Comment by chu11** [comment]
@garlick I wanted to try and reproduce this at home, but then realized, Ubuntu doesn't release 32 bit isos anymore.  Do you remember where you snagged yours?

**Comment by garlick** [comment]
It was the "lubuntu" spin.

**Comment by garlick** [comment]
Sorry, meant to add a URL:
https://lubuntu.net/
 
Specifically the i386 image:
http://cdimage.ubuntu.com/lubuntu/releases/18.10/release/lubuntu-18.10-desktop-i386.iso

**Comment by SteVwonder** [comment]
I'll try and poke at this on the plane ride tomorrow.
