### ISSUE TITLE
vpath build:  fatal error: version.h: No such file or directory

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1834]
I'm seeing this error when doing a VPATH build:
```
In file included from ../../../../src/include/flux/core.h:7:0,
                 from ../../../../src/common/libutil/cronodate.c:31:
../../../../src/common/libflux/flux.h:54:10: fatal error: version.h: No such file or directory
 #include "version.h"
```
I think the problem is that `version.h` is a built source, and therefore is under `builddir` and not `srcdir`. Our Makefiles currently explicitly include `-I$(top_srcdir) -I$(top_srcdir)/src/include`, so we'll probably need to add `-I$(top_builddir)/src/include` at least to every `Makefile.am`.

That being said, I'm not sure why this wasn't caught with `make distcheck` in Travis, so maybe something is wrong just in my environment?

**Comment by grondo** [comment]
>  I'm not sure why yet.

Ah, this is because `version.h` is in `fluxcoreinclude_HEADERS` and so is part of the distribution tarball. 

So during `make distcheck`, I think `version.h` would be found under *both* `srcdir` and `builddir`. I can't think of a case where the two files would be different, but the one under `srcdir` would be the version found during most of the build,  except in the `src/common/libflux` directory, where `-I.` would presumably pick up the `builddir` copy.

**Comment by grondo** [comment]
I propose moving `version.h` to `nodist_fluxcoreinclude_HEADERS` so that the build source is not included in the distribution tarball.

This change will break `make distcheck`, so subsequently `-I$(top_builddir)/src/common/libflux` will need to be added to every `Makefile.am` that might build sources that include `flux/core.h`.

**Comment by grondo** [comment]
And the next problem is that the python `make_binding.py` script can't find `version.h`:
```
make[4]: Entering directory '/usr/src/b/src/bindings/python/_flux'
/usr/bin/python ../../../../../src/bindings/python/make_binding.py --path ../../../../../src/common/libflux \
	--package _flux \
	--modname _core \
	--add_sub '.*va_list.*|||' \
	--ignore_header 'handle_impl' \
	--ignore_header 'macros' \
	--add_long_sub 'FLUX_SEC_TYPE_ALL.*\n.*\),|||FLUX_SEC_TYPE_ALL = 7,'\
	flux.h
Traceback (most recent call last):
  File "../../../../../src/bindings/python/make_binding.py", line 92, in <module>
    process_header(absolute_head)
  File "../../../../../src/bindings/python/make_binding.py", line 80, in process_header
    process_header(m.group(1))
  File "../../../../../src/bindings/python/make_binding.py", line 31, in process_header
    with open(f, 'r') as header:
IOError: [Errno 2] No such file or directory: 'version.h'
Makefile:968: recipe for target '_core_build.py' failed
```

Currently (if I understand the code correctly), `make_binding.py` can only find headers in a single path. I'll try to extend it to allow a search path.
