### ISSUE TITLE
python: adding subprocess.h to flux/core.h causes binding generation error

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2013]
Since libsubprocess is built into libflux-core.so, `subprocess.h` should be added to `flux/core.h`, but this breaks python binding generation, which doesn't seem to like `pid_t` type. 

```
/usr/bin/python _core_build.py
Traceback (most recent call last):
  File "_core_build.py", line 1611, in <module>
    """)
  File "/home/grondo/.local/lib/python2.7/site-packages/cffi/api.py", line 107, in cdef
    self._cdef(csource, override=override, packed=packed)
  File "/home/grondo/.local/lib/python2.7/site-packages/cffi/api.py", line 121, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/home/grondo/.local/lib/python2.7/site-packages/cffi/cparser.py", line 315, in parse
    self._internal_parse(csource)
  File "/home/grondo/.local/lib/python2.7/site-packages/cffi/cparser.py", line 320, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/home/grondo/.local/lib/python2.7/site-packages/cffi/cparser.py", line 278, in _parse
    self.convert_pycparser_error(e, csource)
  File "/home/grondo/.local/lib/python2.7/site-packages/cffi/cparser.py", line 307, in convert_pycparser_error
    raise CDefError(msg)
cffi.error.CDefError: cannot parse "pid_t flux_subprocess_pid (flux_subprocess_t *p);"
<cdef source string>:1527:7: before: flux_subprocess_pid
Makefile:887: recipe for target '_core.c' failed
make[4]: *** [_core.c] Error 1
```

I tried adding `<sys/types.h>` and `<unistd.h>` to ensure `pid_t` was defined within `subprocess.h`, without success. Based on [this stackoverflow](https://stackoverflow.com/questions/33265890/python-cffi-parsing-error-when-defining-a-struct) answer, I tried this:
```diff
ndex 46c6bd43..d56b5003 100644
--- a/src/bindings/python/make_binding.py
+++ b/src/bindings/python/make_binding.py
@@ -205,6 +205,7 @@ void * unpack_long(ptrdiff_t num){{
 ffi.cdef("""
 void * unpack_long(ptrdiff_t num);
 void free(void *ptr);
+typedef int... pid_t;
 
 
         {cdefs}
```

Which works, but I have no idea if that is "correct".

**Comment by garlick** [comment]
Closed by #2014
