### ISSUE TITLE
 msg_handler.c:396: flux_msg_handler_start: Assertion `mh->magic == 0x44433322' failed.

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2281]
One of the failure modes of the reproducer in #2275 is an assertion failure in the broker:
```
lt-flux-broker: msg_handler.c:396: flux_msg_handler_start: Assertion `mh->magic == 0x44433322' failed.
flux-job: flux_open: Connection reset by peer
```

gdb backtrace shows:
```
(gdb) bt
#0  0x00002aaaac218207 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#1  0x00002aaaac2198f8 in __GI_abort () at abort.c:90
#2  0x00002aaaac211026 in __assert_fail_base (
    fmt=0x2aaaac36bea0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x2aaaaad1e6fe "mh->magic == 0x44433322", 
    file=file@entry=0x2aaaaad1e6f0 "msg_handler.c", line=line@entry=396, 
    function=function@entry=0x2aaaaad1e870 <__PRETTY_FUNCTION__.11222> "flux_msg_handler_start") at assert.c:92
#3  0x00002aaaac2110d2 in __GI___assert_fail (
    assertion=assertion@entry=0x2aaaaad1e6fe "mh->magic == 0x44433322", 
    file=file@entry=0x2aaaaad1e6f0 "msg_handler.c", line=line@entry=396, 
    function=function@entry=0x2aaaaad1e870 <__PRETTY_FUNCTION__.11222> "flux_msg_handler_start") at assert.c:101
#4  0x00002aaaaacebd83 in flux_msg_handler_start (mh=<optimized out>)
    at msg_handler.c:396
#5  0x00002aaaaeb704e8 in local_service_start (ls=0x2aaab800e370)
    at local.c:577
#6  service_add_continuation (f=0x2aaab800dec0, arg=0x2aaab800e370)
    at local.c:618
#7  0x00002aaaaad153b3 in ev_invoke_pending (loop=0x2aaab800ab60) at ev.c:3322
#8  0x00002aaaaad188fa in ev_run (loop=0x2aaab800ab60, flags=0) at ev.c:3726
#9  0x00002aaaaacea7f3 in flux_reactor_run (r=0x2aaab800ab40, 
    flags=flags@entry=0) at reactor.c:126
#10 0x00002aaaaeb717a9 in mod_main (h=0x2aaab8001910, argc=<optimized out>, 
    argv=<optimized out>) at local.c:1309
#11 0x000000000040b3ca in module_thread (arg=0x64ba60) at module.c:162
#12 0x00002aaaab66fdd5 in start_thread (arg=0x2aaaaefa4700)
    at pthread_create.c:307
#13 0x00002aaaac2dfead in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

Looks like this might be a pretty obvious race between registration and destruction of a local service in the connector-local when shells are terminating during initialization due to a cancellation. I'll see if I can verify the issue and make a quick fix.

**Comment by grondo** [comment]
I think this patch seems to fix the issue (still running the reproducer):
```diff
 src/modules/connector-local/local.c | 28 ++++++++++++++++++++++++++++
 1 file changed, 28 insertions(+)

diff --git a/src/modules/connector-local/local.c b/src/modules/connector-local/local.c
index 0510ba6..e122854 100644
--- a/src/modules/connector-local/local.c
+++ b/src/modules/connector-local/local.c
@@ -88,6 +88,8 @@ struct local_service {
     char * name;            /* service name                   */
     flux_msg_handler_t *mh; /* local msg handler for requests */
     client_t *client;       /* client which handles requests  */
+    unsigned int active:1;  /* service is active on broker    */
+    unsigned int orphan:1;  /* client has disconnected        */
 };
 
 static void client_destroy (client_t *c);
@@ -574,6 +576,7 @@ error:
 
 static void local_service_start (struct local_service *ls)
 {
+    ls->active = 1;
     flux_msg_handler_start (ls->mh);
 }
 
@@ -602,6 +605,9 @@ static struct local_service *local_service_add (mod_local_ctx_t *ctx,
     return ls;
 }
 
+static void local_service_deregister (mod_local_ctx_t *ctx,
+                                      struct local_service *ls);
+
 static void service_add_continuation (flux_future_t *f, void *arg)
 {
     struct local_service *ls = arg;
@@ -614,10 +620,20 @@ static void service_add_continuation (flux_future_t *f, void *arg)
         saved_errno = errno;
         local_service_remove (ls);
     }
+    else if (ls->orphan) {
+        /* client detached while we were waiting for service.add reply.
+         *  immediately deregister service and remove local
+         *  service from hash:
+         */
+        mod_local_ctx_t *ctx = flux_future_aux_get (f, "ctx");
+        local_service_deregister (ctx, ls);
+        goto out;
+    }
     else
         local_service_start (ls);
     if (client_respond (c, msg, rc < 0 ? saved_errno : 0) < 0)
         flux_log_error (c->ctx->h, "service_add_continuation: client_respond");
+out:
     flux_future_destroy (f);
 }
 
@@ -657,6 +673,7 @@ static int service_add_request (client_t *c, const flux_msg_t *msg)
         goto error;
     }
     flux_future_aux_set (f, "msg", copy, (flux_free_f) flux_msg_destroy);
+    flux_future_aux_set (f, "ctx", ctx, NULL);
     return 0;
 error:
     flux_future_destroy (f);
@@ -861,6 +878,13 @@ static void deregister_service_noreply (mod_local_ctx_t *ctx, const char *name)
         flux_future_aux_set (f, "service_name", s, (flux_free_f) free);
 }
 
+static void local_service_deregister (mod_local_ctx_t *ctx,
+                                      struct local_service *ls)
+{
+    deregister_service_noreply (ctx, ls->name);
+    local_service_remove (ls);
+}
+
 static void client_deregister_services (client_t *c)
 {
     mod_local_ctx_t *ctx = c->ctx;
@@ -873,6 +897,10 @@ static void client_deregister_services (client_t *c)
                 flux_log_error (ctx->h, "client_deregister: zlist_new");
                 break;
             }
+            if (!ls->active) {
+                ls->orphan = 1;
+                break;
+            }
             if (zlist_push (toremove, ls) < 0) {
                 flux_log_error (ctx->h, "client_deregister: zlist_push");
                 break;

```
