### ISSUE TITLE
broker deadlock when unloading job-info

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2503]
@chu11 noted in #2499 that it's possible to deadlock the broker unloading `job-info` when jobs are running.  Specifically, this triggers it on master 4a3ac409977c55ad84c7296cbe5407b2b042535d:
```diff
diff --git a/t/t2204-job-info.t b/t/t2204-job-info.t
index 0f833bf..f5c1d96 100755
--- a/t/t2204-job-info.t
+++ b/t/t2204-job-info.t
@@ -225,6 +225,11 @@ test_expect_success 'flux job list --count works' '
         test_cmp list_count_running.out job_ids_running_head4.out
 '
 
+test_expect_success 'reload the job-info module' '
+        flux module remove job-info &&
+        flux module load job-info
+'
+
 test_expect_success 'cleanup job listing jobs ' '
         for jobid in `cat job_ids_pending.out`; do \
             flux job cancel $jobid; \
```

**Comment by garlick** [comment]
That test gets stuck in the `flux module remove job-info`.

The rank 0 broker seems to be unresponsive, blocked in `zmq_msg_send()`.  Here's a backtrace:
```
0x00007f8523788bf9 in __GI___poll (fds=0x7fffbd1a43e0, nfds=1, timeout=-1)
    at ../sysdeps/unix/sysv/linux/poll.c:29
29	../sysdeps/unix/sysv/linux/poll.c: No such file or directory.
(gdb) bt
#0  0x00007f8523788bf9 in __GI___poll (fds=0x7fffbd1a43e0, nfds=1, timeout=-1)
    at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f8524129bf7 in ?? () from /usr/lib/x86_64-linux-gnu/libzmq.so.5
#2  0x00007f85241072ec in ?? () from /usr/lib/x86_64-linux-gnu/libzmq.so.5
#3  0x00007f852412b932 in ?? () from /usr/lib/x86_64-linux-gnu/libzmq.so.5
#4  0x00007f852412bc48 in ?? () from /usr/lib/x86_64-linux-gnu/libzmq.so.5
#5  0x00007f852414d6f9 in zmq_msg_send ()
   from /usr/lib/x86_64-linux-gnu/libzmq.so.5
#6  0x00007f852438f901 in zframe_send ()
   from /usr/lib/x86_64-linux-gnu/libczmq.so.4
#7  0x00007f8524808feb in flux_msg_sendzsock (sock=<optimized out>, 
    msg=msg@entry=0x563a711b6f70) at message.c:1438
#8  0x0000563a6f23655f in module_sendmsg (p=0x563a708de770, 
    msg=<optimized out>) at module.c:289
#9  0x0000563a6f23669e in module_response_sendmsg (mh=0x563a708b3ee0, 
    msg=0x563a711b7bf0) at module.c:322
#10 0x0000563a6f233fde in broker_response_sendmsg (ctx=0x7fffbd1a4910, 
    msg=0x563a711b7bf0) at broker.c:2000
#11 0x0000563a6f235663 in module_cb (p=0x563a708da780, arg=0x7fffbd1a4910)
    at broker.c:1773
#12 0x00007f8524826651 in check_cb (loop=0x7f8524a60060 <default_loop_struct>, 
    w=0x563a708d8468, revents=<optimized out>) at ev_zmq.c:70
#13 0x00007f85248322b3 in ev_invoke_pending (
    loop=0x7f8524a60060 <default_loop_struct>) at ev.c:3322
#14 0x00007f85248358a9 in ev_run (loop=0x7f8524a60060 <default_loop_struct>, 
    flags=0) at ev.c:3726
#15 0x00007f8524804683 in flux_reactor_run (r=0x563a708b8e30, 
    flags=<optimized out>) at reactor.c:126
#16 0x0000563a6f2336d0 in main (argc=<optimized out>, argv=<optimized out>)
    at broker.c:699
```

The last thing in the broker log is
```
2019-11-01T22:25:57.445750Z broker.debug[0]: rmmod job-info
```

This means `module_stop()` has already successfully sent the `job-info.shutdown` request to the module and returned.  The broker continues on.

In the module thread:
* `job-info.shutdown` request handler calls `flux_reactor_stop()`
* `job-info`'s `flux_reactor_run()` returns
* there is some cleanup
* `mod_main()` returns to the thread wrapper function that called it
* In the wrapper, any requests still queued in the handle are responded to with ENOSYS
* an EXITED keepalive message is sent to the broker
* broker handle is closed (closing module end of ZMQ_PAIR socket)
* the thread wrapper function returns (thread is now in joinable state)

By instrumenting the code I can confirm that the module thread does return.

However, I do not ever see the EXITED keepalive message received in the broker, thus it never tries to join with the thread and destroy the module state.

I instrumented the `service_send()` function in the broker, and I do indeed see two `job-info.eventlog-watch-cancel` requests being sent after the thread has exited (well, "after" being a bit loose since I'm logging from concurrent threads).  

The ZMQ_PAIR [man page](http://api.zeromq.org/4-1:zmq-socket) says:
> When a ZMQ_PAIR socket enters the mute state due to having reached the high water mark for the connected peer, or if no peer is connected, then any zmq_send(3) operations on the socket shall block until the peer becomes available for sending; messages are not discarded.

So since one end is closed, if we send a message on the broker end, that could deadlock the broker.

We'll need to figure out how to prevent that from happening, if that's indeed the problem.

**Comment by garlick** [comment]
I can no longer reproduce this using the method above, so closing.
