### ISSUE TITLE
Questions on Python API

### ISSUE THREAD

**Issue by andre-merzky** [flux-framework/flux-core#2548]
Hi Fluxers, 

First of all, thanks for providing a Python API!  It's not the greatest language for system programming, but it happens to make integration easy for us :-)

[Attached](https://gist.github.com/andre-merzky/a6f1eb33dc5c55c51438e041a0349ae7
) is a Python script which covers most initial functionality I would need for integration with RP - yay!  But some bits look cumbersome, and I wonder if there are easier / better ways to do it.  Here are some questions:

1) Is it possible to start a primary flux instance via the Python API, or is the assumption always that the python module is loaded within an operational `flux env`?  I found `flux-core/t/python/sideflux.py` (and several other places) which all seem to indicate that spawning a flux instance via a shell callout is the preferred way to use - is that correct?

2) Eventually I need to start flux from one Python process, and then use it from another one.  This seems not to be a problem as long `flux env` settings from the started flux instance are applied to the second Python process (correct?).  But having to execute `flux start` in a subprocess makes it somewhat cumbersome to obtain `flux env` output - is there a better way to inspect the flux instance than communicating with the flux shell via stdin/stdout?  Note that `flux kvs` is also not yet available before having the env settings.

`sideflux.py` seems to circumvent this by pre-defining the `FLUX_URI`.  But is the URI alone sufficient?  I would suspect that I need the other env settings also to successfully load the python module and connect?  (I did not try this yet).  

3)  The example seems to hang if I try to submit >500 tasks in one go - but submitting 256 tasks twice works.  Any idea what's up there?  What is the recommended way to obtain a debug trace?  Sorry if I missed that in the docs.  This test was running on a local linux box, FWIW, and used PMI-1.  

4) The `FLUX_URI` points to the local FS.  Is there an option to spawn the flux instance on one node, and to listen for events from another node?  How would I go about that with the Python API?

Many thanks, Andre.

**Comment by SteVwonder** [comment]
Hi @andre-merzky.  Thanks for the quick prototyping and questions.

I migrated the issue over to flux-core since that is where the python bindings live.

Per launching Flux via Python:  Do you want to spin up a Flux instance on a single node? Or do you want a large Flux instance that spans multiple nodes?   If the former, then launching as a subprocess is probably the easiest way to go. If the latter, you will need to either leverage a parallel launcher on your system or create a Flux config file with endpoint information (i.e., ip addresses and ports) so that Flux can bootstrap itself across nodes.  If you are going this route, we can iterate with you on the best way to bootstrap for your use-case.

>  But is the URI alone sufficient? I would suspect that I need the other env settings also to successfully load the python module and connect? 

The `FLUX_URI` is actually sufficient assuming that the flux python modules are in your `PYTHONPATH`.    The `flux start` command conveniently adds the right path to `PYTHONPATH` so that everything is consistent, but it is not necessary to go through that command or `flux env`/`flux proxy`.   If you have the `FLUX_URI` as a variable in the second python process, you can connect to the running instance via the `Flux` constructor like so:

```
import flux
handle = flux.Flux(url=FLUX_URI)
...
```

> The example seems to hang if I try to submit >500 tasks in one go - but submitting 256 tasks twice works. Any idea what's up there? What is the recommended way to obtain a debug trace? Sorry if I missed that in the docs. This test was running on a local linux box, FWIW, and used PMI-1.

As @dongahn suggests, I'll open a separate issue to track this particular problem.

**Comment by andre-merzky** [comment]
> Once you get the FLUX_URI for the target instance, you can use `flux proxy` to connect to the instance.

Ah, great - that's what I was looking for indeed!  And yes, it would be helpful to fetch that environment from within Python.

> flux dmesg, logfile

I'll have a look! And also thanks for the hints on constructing the ssh://... uri, that makes sense.

> Per launching Flux via Python: Do you want to spin up a Flux instance on a single node? Or do you want a large Flux instance that spans multiple nodes? 

Right now I play on a local machine.  Eventually I want to move to HPC resources (Summit and Fontera) and see how it scales, to compare to our task launching via jsrun (summit) and PRRTE (summit, frontera)  (prrte @ frontera is not yet working for us though).  

> parallel launcher ...  config file ...

I can't yet appreciate the difference I'm afraid, but providing a config file seems like a reasonable easy approach.  When we get the job allocation we usually inspect the node configuration etc anyway and build our on config map out of it - spitting out an additional config file for flux would be straight forward.  Do you happen to have a pointer at the format spec or some example?  Thanks!

> `import flux`
> `handle = flux.Flux(url=FLUX_URI)`

Ah, excellent - that will do of course.

Thanks both, that looks great :-)  I am not sure why, but we missed for a long time that Flux can be used in userspace - we always considered it a system level effort.  I wish we would have learned this earlier...  Oh well.  Either way, flux is an exciting system! :+1:

**Comment by dongahn** [comment]
> Eventually I want to move to HPC resources (Summit and Fontera) and see how it scales, to compare to our task launching via jsrun (summit) and PRRTE (summit, frontera) (prrte @ frontera is not yet working for us though).

By the time you get there, we need to discuss. We should if you can model after some of the existing workflows running on Sierra and Summit. 

You may want to look at this year's paper on MuMMi which used flux to get the throughout and co-scheduling they needed. This was presented yesterday at SC and is a best paper candidate. 

They used a bit of nesting. But if you need extreme throughout, we can use nesting even more aggressively. 

Also at the moment there are issues with PMIx and Spectrum which we are resolving. We will need a bit of handholding.

**Comment by dongahn** [comment]
> we missed for a long time that Flux can be used in userspace - we always considered it a system level effort.

Yeah... a key design parameter for flux is that we use the same software infrastructure for both system and user space resource management and scheduling.

Thank you for taking time to look into this. I am sure we will discuss more going forward...

**Comment by andre-merzky** [comment]
> By the time you get there, we need to discuss. We should if you can model after some of the existing workflows running on Sierra and Summit.

Sure, and we would like to do so.  And I'm aware that this will take time and we won't get there overnight, no worries.  But with PRRTE and Flux there are finally some viable alternatives to process based options like aprun, ibrun, srun, mpirun/mpiexec and the like which always limited our ability for task placement at scale.

At the moment I am most interested in understanding the semantic mapping between the different layers (task state model, event models, load balancing, resilience), and less concerned about actual performance.  And we'd definitely would appreciate guidance on how specific machines and/or use cases are best approached with Flux.


> You may want to look at this year's paper on MuMMi which used flux to get the throughout and co-scheduling they needed. This was presented yesterday at SC and is a best paper candidate.

This would be https://sc19.supercomputing.org/presentation/?id=pap384&sess=sess165 ?  Thanks for the pointer!


> They used a bit of nesting. But if you need extreme throughout, we can use nesting even more aggressively.

Our throughput requirements vary wildly with the use cases we support.  We tend to stress-test with the high-throughput cases (short single-core tasks + scale), but most real use cases in our science drivers end up using moderate sized tasks which use up to several nodes.  But there are always a few use cases which are pushing us toward throughput...


> Also at the moment there are issues with PMIx and Spectrum which we are resolving. We will need a bit of handholding.

Ack, and I am not surprised, PMIx is young and evolving.  We had the good fortune to get close support from ORNL on Summit and PRRTE/PMIx: those needed also a couple of iterations until we managed to run our experiments. I have no illusions that this would be any different on other machines. 

Thank you!

**Comment by andre-merzky** [comment]
> The `FLUX_URI` is actually sufficient assuming that the flux python modules are in your `PYTHONPATH`.

Almost: it also needs `PATH` set so that the flux executable is found, otherwise I obtain:
```
bash: flux: command not found
Traceback (most recent call last):
  File "./rp_flux.py", line 126, in <module>
    use_flux(flux_url)
  File "./rp_flux.py", line 93, in use_flux
    h = flux.Flux(url=flux_url)
  File "/home/merzky/projects/flux/install/lib/flux/python2.7/flux/__init__.py", line 19, in Flux
    return flux.core.handle.Flux(*args, **kwargs)
  File "/home/merzky/projects/flux/install/lib/flux/python2.7/flux/core/handle.py", line 42, in __init__
    self.handle = raw.flux_open(url, flags)
  File "/home/merzky/projects/flux/install/lib/flux/python2.7/flux/wrapper.py", line 217, in __call__
    err, "{}: {}".format(errno.errorcode[err], os.strerror(err))
EnvironmentError: [Errno 104] ECONNRESET: Connection reset by peer
```

Not a problem, just wanted to mention it.  Otherwise switching `local://` to `ssh://hostname` works as described - neat :-)

**Comment by andre-merzky** [comment]
Thanks for all the help and advise!  I renamed the ticket to reflect the remaining open point, but wanted to mention that this is low priority (from my end), as I have a working solution via shell callouts.

**Comment by grondo** [comment]
Added `design` label to avoid stale-bot.
