### ISSUE TITLE
UBSan: errors in veb.c

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2574]
Since we have sanitizers "working" in flux-core, I gave `-fsanitize=undefined` a try. I immediately hit this error, which I haven't looked into yet:

```
veb.c:43:11: runtime error: left shift of negative value -1
veb.c:80:12: runtime error: left shift of 255 by 24 places cannot be represented in type 'int'
```

I do not know if this is a false positive or not. But thought I'd open an issue anyway just for interest.

Full test_veb.t output:
(More errors found below, the two above are what was hit in real code)

```
ok 1 - empty_pred_test1 vebnew OK
ok 2
ok 3
veb.c:43:11: runtime error: left shift of negative value -1
ok 4
ok 5
ok 6
ok 7
ok 8
ok 9
ok 10 - empty_pred_test2 vebnew OK
ok 11
ok 12
ok 13
ok 14
ok 15
ok 16
ok 17
ok 18
ok 19
ok 20 - empty_pred_load_test1 vebnew OK
ok 21 - empty_pred_load_test1 no errors
ok 22 - empty_pred_load_test2 vebnew OK
ok 23 - empty_pred_load_test2 correct count
ok 24 - empty_succ_test1 vebnew OK
ok 25
ok 26
ok 27
ok 28
ok 29
ok 30
ok 31
ok 32
ok 33 - empty_succ_test2 vebnew OK
ok 34
ok 35
ok 36
ok 37
ok 38
ok 39
ok 40
ok 41
ok 42
ok 43 - empty_succ_load_test1 vebnew OK
ok 44 - empty_succ_load_test1 random fill OK
ok 45 - empty_succ_load_test1 no errors
ok 46 - empty_succ_load_test2 vebnew OK
ok 47 - empty_succ_load_test2 correct count
ok 48 - full_pred_test1 vebnew OK
ok 49
ok 50
ok 51
ok 52
ok 53
ok 54
ok 55
ok 56
ok 57 - full_pred_load_test1 vebnew OK
ok 58 - full_pred_load_test1 random fill OK
ok 59 - full_pred_load_test1 no errors
ok 60 - full_pred_load_test2 vebnew OK
ok 61 - full_pred_load_test2 correct count
ok 62 - full_succ_test1 vebnew OK
ok 63
ok 64
ok 65
ok 66
ok 67
ok 68
ok 69
ok 70
ok 71 - full_succ_load_test1 vebnew OK
ok 72 - full_succ_load_test1 random fill OK
ok 73 - full_succ_load_test1 no errors
ok 74 - full_succ_load_test2 vebnew OK
ok 75 - full_succ_load_test2 correct count
veb_mach.c:8:9: runtime error: passing zero to clz(), which is not a valid argument
ok 76 - test_empty_init: 1 all clear
ok 77 - test_empty_init: 2 all clear
ok 78 - test_empty_init: 4 all clear
ok 79 - test_empty_init: 8 all clear
ok 80 - test_empty_init: 16 all clear
ok 81 - test_empty_init: 32 all clear
ok 82 - test_empty_init: 64 all clear
ok 83 - test_empty_init: 128 all clear
ok 84 - test_empty_init: 256 all clear
ok 85 - test_empty_init: 512 all clear
ok 86 - test_empty_init: 1024 all clear
ok 87 - test_empty_init: 2048 all clear
ok 88 - test_empty_init: 4096 all clear
ok 89 - test_empty_init: 8192 all clear
ok 90 - test_empty_init: 16384 all clear
ok 91 - test_empty_init: 32768 all clear
ok 92 - test_empty_init: 65536 all clear
ok 93 - test_empty_init: 131072 all clear
ok 94 - test_empty_init: 262144 all clear
ok 95 - test_empty_init: 524288 all clear
veb_mach.c:8: runtime error: passing zero to clz(), which is not a valid argument
ok 96 - test_full_init: 1 all set
ok 97 - test_full_init: 2 all set
ok 98 - test_full_init: 4 all set
ok 99 - test_full_init: 8 all set
ok 100 - test_full_init: 16 all set
veb.c:80:12: runtime error: left shift of 255 by 24 places cannot be represented in type 'int'
ok 101 - test_full_init: 32 all set
ok 102 - test_full_init: 64 all set
ok 103 - test_full_init: 128 all set
ok 104 - test_full_init: 256 all set
ok 105 - test_full_init: 512 all set
ok 106 - test_full_init: 1024 all set
ok 107 - test_full_init: 2048 all set
ok 108 - test_full_init: 4096 all set
ok 109 - test_full_init: 8192 all set
ok 110 - test_full_init: 16384 all set
ok 111 - test_full_init: 32768 all set
ok 112 - test_full_init: 65536 all set
ok 113 - test_full_init: 131072 all set
ok 114 - test_full_init: 262144 all set
ok 115 - test_full_init: 524288 all set
# M=32 vebsize=4
# vebpred=31
ok 116 - M=32: vebpred 31 returned 31
1..116

```

**Comment by grondo** [comment]
This seems to quiet the shift errors, though I'm not 100% confident of that case of `D[i]` to `uint`. All tests do seem to still pass.

```diff
index 935fd92ee..1cc1eb725 100644
--- a/src/common/libutil/veb.c
+++ b/src/common/libutil/veb.c
@@ -40,7 +40,7 @@ zeros(uint k)
 	assert (k <= WORD);
 	if (k==WORD) /* left shift >= width of operand is undefined */
 		return 0;
-	return ~0<<k;
+	return ~0U<<k;
 }
 
 static uint
@@ -77,7 +77,7 @@ decode(uchar D[], uint b)
 
 	assert (8*(b-1) < WORD);
 	for (i = 0; i < b; ++i)
-		x |= D[i]<<8*i;
+		x |= ((uint)D[i])<<8*i;
 	return x;
 }
 
```

Additionally hit the following error: argument of `0` to `clz()` and `ctz()` is undefined
```
$ UBSAN_OPTIONS=print_stacktrace=1:print_summary=1:halt_on_error=1 ./test_veb.t 
k 71 - full_succ_load_test1 vebnew OK
ok 72 - full_succ_load_test1 random fill OK
ok 73 - full_succ_load_test1 no errors
ok 74 - full_succ_load_test2 vebnew OK
ok 75 - full_succ_load_test2 correct count
veb_mach.c:8:9: runtime error: passing zero to clz(), which is not a valid argument
    #0 0x5596d3ff2f70 in clz /usr/src/src/common/libutil/veb_mach.c:8
    #1 0x5596d3ff2f70 in fls /usr/src/src/common/libutil/veb_mach.c:20
    #2 0x5596d3ff2f70 in vebnew /usr/src/src/common/libutil/veb.c:217
    #3 0x5596d3ff4fa1 in test_empty_init test/veb.c:477
    #4 0x5596d3ff304c in main test/veb.c:532
    #5 0x7fc66955cb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #6 0x5596d3ff3089 in _start (/usr/src/src/common/libutil/test_veb.t+0x2089)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior veb_mach.c:8:9 in 
```

this quiets that ubsan error:

```diff
diff --git a/src/common/libutil/veb_mach.c b/src/common/libutil/veb_mach.c
index 984057a48..2da35bbae 100644
--- a/src/common/libutil/veb_mach.c
+++ b/src/common/libutil/veb_mach.c
@@ -5,13 +5,13 @@
 static uint
 clz(uint x)
 {
-	return __builtin_clz(x);
+	return x != 0 ? __builtin_clz(x) : sizeof (x);
 }
 
 static uint
 ctz(uint x)
 {
-	return __builtin_ctz(x);
+	return x != 0 ? __builtin_ctz(x) : sizeof (x);
 }
 
 static uint

```

**Comment by garlick** [comment]
We should probably go ahead with @grondo's proposed changes.
