### ISSUE TITLE
Python: OSError: Invalid Argument and Invalid Protocol

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-core#2933]
I have been working with @dongahn and @SteVwonder doing some UQP/Flux scaling studies, and I've been trying to use the python bindings. However, I'm getting two different errors, and the tracebacks/error messages are not very helpful to me:

```
Exception in thread creator_thread:
Traceback (most recent call last):
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()

   [ ... ]

    self._job_id = flux.job.submit(self.broker, jobspec, waitable=True)
  File "/collab/usr/global/tools/flux/toss_3_x86_64_ib/flux-0.17.0-pre-ft/lib/flux/python3.6/flux/job.py", line 196, in submit
    return future.get_id()
  File "/collab/usr/global/tools/flux/toss_3_x86_64_ib/flux-0.17.0-pre-ft/lib/flux/python3.6/flux/job.py", line 92, in get_id
    return submit_get_id(self)
  File "/collab/usr/global/tools/flux/toss_3_x86_64_ib/flux-0.17.0-pre-ft/lib/flux/python3.6/flux/util.py", line 50, in func_wrapper
    six.reraise(*exception_tuple)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/collab/usr/global/tools/flux/toss_3_x86_64_ib/flux-0.17.0-pre-ft/lib/flux/python3.6/flux/util.py", line 37, in func_wrapper
    return func(calling_obj, *args, **kwargs)
  File "/collab/usr/global/tools/flux/toss_3_x86_64_ib/flux-0.17.0-pre-ft/lib/flux/python3.6/flux/job.py", line 156, in submit_get_id
    future.wait_for()  # ensure the future is fulfilled
  File "/collab/usr/global/tools/flux/toss_3_x86_64_ib/flux-0.17.0-pre-ft/lib/flux/python3.6/flux/future.py", line 137, in wait_for
    self.pimpl.wait_for(timeout)
  File "/collab/usr/global/tools/flux/toss_3_x86_64_ib/flux-0.17.0-pre-ft/lib/flux/python3.6/flux/wrapper.py", line 347, in wrap_class
    return new_fun(self_renamed, *args, **kwargs)
  File "/collab/usr/global/tools/flux/toss_3_x86_64_ib/flux-0.17.0-pre-ft/lib/flux/python3.6/flux/util.py", line 50, in func_wrapper
    six.reraise(*exception_tuple)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/collab/usr/global/tools/flux/toss_3_x86_64_ib/flux-0.17.0-pre-ft/lib/flux/python3.6/flux/util.py", line 37, in func_wrapper
    return func(calling_obj, *args, **kwargs)
  File "/collab/usr/global/tools/flux/toss_3_x86_64_ib/flux-0.17.0-pre-ft/lib/flux/python3.6/flux/wrapper.py", line 221, in __call__
    "{}: {}".format(errno.errorcode[errnum], os.strerror(errnum)),
OSError: [Errno 22] EINVAL: Invalid argument
```

The other error I was getting was "Invalid Protocol", but unfortunately I seem to have wiped the traceback I got and I am having trouble reproducing it. It came from the `flux.job.wait` function, though. I have also sometimes gotten just hangs with no errors. And one time I just got a core dump from Python... nice!

My best guess is that this is coming from the fact that I am having one Python thread (created from the `threading` module) submit jobs to a `flux.Flux` instance, while another thread waits for jobs to complete on the same instance. Is that supported usage or are `flux.Flux` instances not thread-safe?

**Comment by grondo** [comment]
> Is that supported usage or are flux.Flux instances not thread-safe?

In general that is not going to be safe.  Try creating a new flux.Flux() for each thread and see if that makes things more stable.

**Comment by jameshcorbett** [comment]
I tried that, and I would have sworn it made the `wait` calls wait indefinitely, but I just tried it again (several times) and it worked. My bad. Thanks @grondo.

**Comment by grondo** [comment]
No problem! Let us know if you hit any other issues with your setup. Happy to help!
