### ISSUE TITLE
issues building on 32-bit armv7l

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3018]
I ran into a couple of build issues on a raspberry pi.

pointer to function used instead of function result:
```
bulk-exec.c: In function ‘subprocess_destroy_finish’:
bulk-exec.c:257:25: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
                         (uintmax_t) flux_subprocess_pid,
                         ^
```

jobid needs the usual uintmax_t cast and %llu
```
job-exec.c: In function ‘exception_cb’:
job-exec.c:1053:53: error: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘flux_jobid_t’ {aka ‘long long unsigned int’} [-Werror=format=]
         flux_log (h, LOG_DEBUG, "exec aborted: id=%ld", id);
                                                   ~~^   ~~
                                                   %lld
  CC       exec.lo
```

And finally I haven't looked to see what's going wrong with python binding generation
```
Making all in _flux
make[4]: Entering directory '/home/garlick/proj/flux-core/src/bindings/python/_flux'
/usr/bin/python3 ./make_clean_header.py \
  --path ../../../.. \
  --search ../../../../src/common/libflux \
  --additional_headers \
      src/bindings/python/_flux/callbacks.h \
      src/common/libdebugged/debugged.h \
  --output _core_clean.h \
  src/include/flux/core.h
gcc -E  '-D__attribute__(...)=' _core_clean.h\
  | sed -e '/^# [0-9]*.*/d' > _core_preproc.h
/usr/bin/python3 _core_build.py _core_preproc.h
generating _core.c
Traceback (most recent call last):
  File "_core_build.py", line 38, in <module>
    ffi.emit_c_code("_core.c")
  File "/usr/lib/python3/dist-packages/cffi/api.py", line 692, in emit_c_code
    c_file=filename, call_c_compiler=False, **kwds)
  File "/usr/lib/python3/dist-packages/cffi/recompiler.py", line 1509, in recompile
    verbose=compiler_verbose)
  File "/usr/lib/python3/dist-packages/cffi/recompiler.py", line 1414, in make_c_source
    verbose)
  File "/usr/lib/python3/dist-packages/cffi/recompiler.py", line 1389, in _make_c_or_py_source
    recompiler.collect_step_tables()
  File "/usr/lib/python3/dist-packages/cffi/recompiler.py", line 239, in collect_step_tables
    self._generate("ctx")
  File "/usr/lib/python3/dist-packages/cffi/recompiler.py", line 224, in _generate
    method(tp, realname)
  File "/usr/lib/python3/dist-packages/cffi/recompiler.py", line 1031, in _generate_cpy_anonymous_ctx
    self._enum_ctx(tp, name)
  File "/usr/lib/python3/dist-packages/cffi/recompiler.py", line 1114, in _enum_ctx
    basetp = tp.build_baseinttype(self.ffi, [])
  File "/usr/lib/python3/dist-packages/cffi/model.py", line 555, in build_baseinttype
    "or 'unsigned long'" % self._get_c_name())
cffi.CDefError: anonymous $enum_$19: enum $19 values don't all fit into either 'long' or 'unsigned long'
make[4]: *** [Makefile:943: _core.c] Error 1
```

**Comment by grondo** [comment]
Maybe those job-exec debug logs should just be dropped. Sorry about that!

**Comment by grondo** [comment]
I'm assuming these still aren't issues.
