### ISSUE TITLE
python 3 virtual env: make in flux-core/etc fails

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3075]
hit the following when running make in flux-core/etc

```
(py3) catalyst159|~/chaos/git/flux-framework/flux-core/etc 134>make
  GEN      flux/help.d/core.json
Traceback (most recent call last):
  File "./gen-cmdhelp.py", line 39, in <module>
    for line in f:
  File "/g/g0/achu/chaos/git/flux-framework/flux-core/py3/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1308: ordinal not in range(128)
make: *** [flux/help.d/core.json] Error 1
```

seems to be hitting it on flux-event.rst, which appears to have some unicode in there.

so the script is assuming all files are encoded in ascii, thus hitting an issue when it finds non-ascii.

the following seems to fix things, dunno if its right

```
diff --git a/etc/gen-cmdhelp.py b/etc/gen-cmdhelp.py
index 2e6fd50..a8871ec 100644
--- a/etc/gen-cmdhelp.py
+++ b/etc/gen-cmdhelp.py
@@ -34,7 +34,7 @@ for (path, cmd, descr, author, section) in man_pages:
     if section is not 1 or path in visited:
         continue
     visited[path] = True
-    with open(f"{docsdir}/{path}.rst", "r") as f:
+    with open(f"{docsdir}/{path}.rst", "r", encoding='utf-8') as f:
         include_flag = False
         for line in f:
             line = line.rstrip("\n")
```

**Comment by grondo** [comment]
This is with Python 3? What was your LANG and/or LC_ALL?

The fix looks good to me.

**Comment by chu11** [comment]
I eventually realized `LC_ALL` was set to `C`. I have no idea what Livermore Computing script is setting this environment variable for me!

I'm going to close this issue and collapse it into #3071 as a general LANG/LC issue.
