### ISSUE TITLE
early exit from initial program causes errors, occasional hang

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3235]
If the initial program of an instance exits before resource.acquire is complete, then there is a mass of errors (probably from the launch of `flux hwloc reload`). At least once I've seen the instance hang at exit when this occurs, though I haven't found that to be reproducible.

To reproduce, just run `flux mini alloc -n <size> /bin/true`:
```
ƒ(s=208,builddir) grondo@fluke6:~/git/flux-core.git$ flux mini alloc -n208 /bin/true
2020-09-28T22:01:23.652791Z sched-simple.err[0]: resource.acquire failed: resource discovery failed or interrupted
2020-09-28T22:01:23.655104Z sched-simple.crit[0]: fatal error: No such file or directory
2020-09-28T22:01:24.507674Z lt-flux-exec.err[0]: remote_continuation_cb: flux_rpc_get_unpack: No route to host
2020-09-28T22:01:24.688742Z lt-flux-exec.err[0]: remote_continuation_cb: flux_rpc_get_unpack: No route to host
2020-09-28T22:01:24.688884Z lt-flux-exec.err[0]: remote_continuation_cb: flux_rpc_get_unpack: No route to host
2020-09-28T22:01:24.688969Z lt-flux-exec.err[0]: remote_continuation_cb: flux_rpc_get_unpack: No route to host
2020-09-28T22:01:24.689049Z lt-flux-exec.err[0]: remote_continuation_cb: flux_rpc_get_unpack: No route to host
2020-09-28T22:01:24.689128Z lt-flux-exec.err[0]: remote_continuation_cb: flux_rpc_get_unpack: No route to host
2020-09-28T22:01:24.689216Z lt-flux-exec.err[0]: remote_continuation_cb: flux_rpc_get_unpack: No route to host
2020-09-28T22:01:24.616804Z broker.err[81]: server_signal_subprocess: flux_subprocess_kill: Invalid argument
...
[hang]
```

**Comment by grondo** [comment]
Some more data from `flux-dmesg` after the hang:

```
2020-09-28T22:40:03.963898Z resource.debug[0]: monitor-batch: goodbye 26-30,63-94
2020-09-28T22:40:03.973688Z resource.debug[0]: reslog_cb: offline event posted
2020-09-28T22:40:04.069913Z resource.debug[0]: monitor-batch: goodbye 31-37,39-51
2020-09-28T22:40:04.076111Z resource.debug[0]: reslog_cb: offline event posted
2020-09-28T22:40:04.286945Z resource.debug[0]: monitor-batch: goodbye 13-14
2020-09-28T22:40:04.288696Z resource.debug[0]: reslog_cb: offline event posted
2020-09-28T22:40:04.406222Z resource.debug[0]: monitor-batch: goodbye 15-17,19-25
2020-09-28T22:40:04.408255Z resource.debug[0]: reslog_cb: offline event posted
2020-09-28T22:40:04.660953Z resource.debug[0]: monitor-batch: goodbye 6
2020-09-28T22:40:04.662880Z resource.debug[0]: reslog_cb: offline event posted
2020-09-28T22:40:04.765903Z resource.debug[0]: monitor-batch: goodbye 7,9-12
2020-09-28T22:40:04.767703Z resource.debug[0]: reslog_cb: offline event posted
2020-09-28T22:40:05.144297Z resource.debug[0]: monitor-batch: goodbye 4-5
2020-09-28T22:40:05.145985Z resource.debug[0]: reslog_cb: offline event posted
2020-09-28T22:40:05.435827Z resource.debug[0]: monitor-batch: goodbye 2
2020-09-28T22:40:05.437526Z resource.debug[0]: reslog_cb: offline event posted
```

```
ƒ(s=208) grondo@fluke6:~$ flux kvs get resource.eventlog
{"timestamp":1601332797.4868393,"name":"resource-init","context":{"restart":false,"hwloc-discover":false,"online":"0","drain":"","exclude":""}}
{"timestamp":1601332798.6088202,"name":"online","context":{"idset":"1-2"}}
{"timestamp":1601332799.139837,"name":"online","context":{"idset":"3,6"}}
{"timestamp":1601332799.2659383,"name":"online","context":{"idset":"4-5"}}
{"timestamp":1601332799.6673653,"name":"online","context":{"idset":"7-8,13-14"}}
{"timestamp":1601332799.9457841,"name":"online","context":{"idset":"9-12"}}
{"timestamp":1601332800.2469437,"name":"online","context":{"idset":"15-16"}}
{"timestamp":1601332800.3638225,"name":"online","context":{"idset":"17-18,27-30"}}
{"timestamp":1601332800.5654118,"name":"online","context":{"idset":"19-22,25-26"}}
{"timestamp":1601332800.6703596,"name":"online","context":{"idset":"23-24"}}
{"timestamp":1601332800.8383982,"name":"online","context":{"idset":"31-32"}}
{"timestamp":1601332800.9666362,"name":"online","context":{"idset":"33-38,55-62"}}
{"timestamp":1601332801.2196252,"name":"online","context":{"idset":"39-46,51-54"}}
{"timestamp":1601332801.3259363,"name":"online","context":{"idset":"47-50"}}
{"timestamp":1601332801.4635973,"name":"online","context":{"idset":"63-64"}}
{"timestamp":1601332801.5883884,"name":"online","context":{"idset":"65-70"}}
{"timestamp":1601332801.7361476,"name":"online","context":{"idset":"71-78,111-126"}}
{"timestamp":1601332801.8882892,"name":"online","context":{"idset":"79-86,103-110"}}
{"timestamp":1601332802.0111406,"name":"online","context":{"idset":"87-102,127-130"}}
{"timestamp":1601332802.2655382,"name":"online","context":{"idset":"131-142"}}
{"timestamp":1601332802.4850175,"name":"online","context":{"idset":"143-158"}}
{"timestamp":1601332802.571377,"name":"hwloc-discover-finish","context":{"loaded":false}}
{"timestamp":1601332802.6363866,"name":"online","context":{"idset":"159-174"}}
{"timestamp":1601332802.7675858,"name":"online","context":{"idset":"175-207"}}
{"timestamp":1601332802.7713664,"name":"hwloc-discover-start","context":{"pid":13018}}
{"timestamp":1601332803.3780735,"name":"offline","context":{"idset":"104-126,191-207"}}
{"timestamp":1601332803.6944163,"name":"offline","context":{"idset":"52-62,95-103,127-190"}}
{"timestamp":1601332803.9639282,"name":"offline","context":{"idset":"26-30,63-94"}}
{"timestamp":1601332804.0699308,"name":"offline","context":{"idset":"31-37,39-51"}}
{"timestamp":1601332804.2869608,"name":"offline","context":{"idset":"13-14"}}
{"timestamp":1601332804.4062448,"name":"offline","context":{"idset":"15-17,19-25"}}
{"timestamp":1601332804.6609704,"name":"offline","context":{"idset":"6"}}
{"timestamp":1601332804.7659178,"name":"offline","context":{"idset":"7,9-12"}}
{"timestamp":1601332805.144315,"name":"offline","context":{"idset":"4-5"}}
{"timestamp":1601332805.4358442,"name":"offline","context":{"idset":"2"}}
```

**Comment by garlick** [comment]
summing up the offline idsets, I get 2,4-7,9-17,19-37,39-207 (size = 208).  Missing are 0,1,3,8,18,36.

That sequence makes up a set of TBON descendants for k=2.  0 is waiting for 1, 1 for 3, 3 for 8, 8 for 18, 18 for 36, and 36 for some peer I didn't calculate.

So this failure exhibits somewhat like #3248, which is an intermittent failure on centos 7 in travis.

**Comment by garlick** [comment]
I'm able to reproduce this by running a size=16 instance with /bin/true as the initial program over and over in the centos 7 docker image. It looks like the last node in the stuck tree of brokers is really stuck - got a backtrace:
```
0  0x00007f3abd0e3c3d in poll () from /lib64/libc.so.6
#1  0x00007f3abdf7ea7a in zmq::signaler_t::wait(int) () from /lib64/libzmq.so.5
#2  0x00007f3abdf63820 in zmq::mailbox_t::recv(zmq::command_t*, int) ()
   from /lib64/libzmq.so.5
#3  0x00007f3abdf7fc3a in zmq::socket_base_t::process_commands(int, bool) ()
   from /lib64/libzmq.so.5
#4  0x00007f3abdf8003f in zmq::socket_base_t::send(zmq::msg_t*, int) ()
   from /lib64/libzmq.so.5
#5  0x00007f3abdf96a8c in s_sendmsg(zmq::socket_base_t*, zmq_msg_t*, int) ()
   from /lib64/libzmq.so.5
#6  0x00007f3abe1d5208 in zframe_send () from /lib64/libczmq.so.3
#7  0x00007f3abe6883e4 in flux_msg_sendzsock (sock=sock@entry=0x1c82e70,
    msg=msg@entry=0x1cba4c0) at message.c:1596
#8  0x000000000040de92 in overlay_mcast_child_one (uuid=0x1c7a3a0 "9",
    msg=0x1cbff10, zsock=0x1c82e70) at overlay.c:294
#9  overlay_mcast_child (ov=0x1c7c4c0, msg=msg@entry=0x1cbff10)
    at overlay.c:314
#10 0x000000000040903c in handle_event (ctx=ctx@entry=0x7ffe0c7facd0,
    msg=msg@entry=0x1cbff10) at broker.c:1559
#11 0x000000000040a23f in parent_cb (ov=<optimized out>, sock=<optimized out>,
    arg=0x7ffe0c7facd0) at broker.c:1600
#12 0x00007f3abe6a30d5 in check_cb (loop=0x7f3abe8de1a0 <default_loop_struct>,
    w=0x1c99768, revents=<optimized out>) at ev_zmq.c:73
#13 0x00007f3abe6ac255 in ev_invoke_pending (
    loop=0x7f3abe8de1a0 <default_loop_struct>) at ev.c:3372
#14 0x00007f3abe6afda7 in ev_run (loop=0x7f3abe8de1a0 <default_loop_struct>,
    flags=0) at ev.c:3775
#15 0x00007f3abe683b53 in flux_reactor_run (r=0x1c7a340, flags=flags@entry=0)
    at reactor.c:126
```
