### ISSUE TITLE
Python binding: flux ceased to work in threads (other than `MainThread`)

### ISSUE THREAD

**Issue by andre-merzky** [flux-framework/flux-core#3264]
Commit de37b5cc44c48f24ed86f986a7c9ca999f102a54 sets a default signal handler for `SIGINT` while calling into C to make the call interruptible.  I empathize with that rationale - but `signal.signal` cannot  be called into threads other than `MainThread`:

```py
1602601972.797 : agent_scheduling.0000 : 8009  : 140281614477056 : ERROR    : worker thread initialization failed
Traceback (most recent call last):
  File "/home/merzky/radical/radical.pilot.test/ve3/lib/python3.7/site-packages/radical/pilot/utils/component.py", line 476, in _worker_thread
    self._initialize()
  File "/home/merzky/radical/radical.pilot.test/ve3/lib/python3.7/site-packages/radical/pilot/utils/component.py", line 614, in _initialize
    self.initialize()
  File "/home/merzky/radical/radical.pilot.test/ve3/lib/python3.7/site-packages/radical/pilot/agent/scheduler/base.py", line 287, in initialize
    self._configure()
  File "/home/merzky/radical/radical.pilot.test/ve3/lib/python3.7/site-packages/radical/pilot/agent/scheduler/flux.py", line 68, in _configure
    self.work(unit)
  File "/home/merzky/radical/radical.pilot.test/ve3/lib/python3.7/site-packages/radical/pilot/agent/scheduler/flux.py", line 201, in work
    jid = flux_job.submit(self._flux, js, debug=True)
  File "/home/merzky/projects/flux/install/lib/python3.6/site-packages/flux/job/submit.py", line 126, in submit
    return future.get_id()
  File "/home/merzky/projects/flux/install/lib/python3.6/site-packages/flux/job/submit.py", line 22, in get_id
    return submit_get_id(self)
  File "/home/merzky/projects/flux/install/lib/python3.6/site-packages/flux/util.py", line 40, in func_wrapper
    return func(calling_obj, *args, **kwargs)
  File "/home/merzky/projects/flux/install/lib/python3.6/site-packages/flux/job/submit.py", line 86, in submit_get_id
    future.wait_for()  # ensure the future is fulfilled
  File "/home/merzky/projects/flux/install/lib/python3.6/site-packages/flux/util.py", line 67, in func_wrapper
    signal.signal(signal.SIGINT, signal.SIG_DFL)
  File "/usr/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

My hunch would be that you may want to shield this by
```py
import threading as mt
if isinstance(mt.current_thread(), mt._MainThread):
```
and thus not resetting the signal handlers in subthreads at all.  `KeyboardInterrupt` should still arrive in the main thread.  Now that is less than ideal, since my subthreads won't get interrupted - but that's now my problem, not yours ;-)  (we mark all such threads as daemon threads so that the application can terminate timely).

Well, threading and signalling in Python are a bit messy (to phrase it kindly), so I may well be missing the target with my suggestion...

**Comment by grondo** [comment]
Wow! Good catch. I totally take the blame for that addition (without it our Python-based utilities become uninterruptible when blocked in the Flux C API). I can only ask forgiveness since I do not know Python very well.

If you'd like, feel free to submit a PR and we'll merge it asap, o/w I can work one up later today.

Thanks again!

**Comment by grondo** [comment]
Oh, I guess it might also be good to have either @SteVwonder or @trws comment as well.

**Comment by andre-merzky** [comment]
No worries, @grondo - threading and signalling in Python is a bottomless pit I'm afraid... :-/  I opened #3266, it solves my problem, I am back on flux-core - master now :-)

**Comment by trws** [comment]
It is indeed.  If the issue with being uninterruptible is one of performance or similar and not correctness or ability to clean up, I'd say this is fine.  If they need to be interruptible though that may mean needing to come up with some other way to facilitate it.  Possibly having a C function that sets a signal handler on the way to the actual target C function?  I'm not sure.
