### ISSUE TITLE
zmq_bind fails on ipv6 link-local addresses

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3378]
Hit this while testing a Fedora 33 builder in Github Actions builder:

```
expecting success: 
  	flux start ${ARGS} -s2 -o,--setattr=tbon.endpoint=tcp://%h:* \
  		flux getattr tbon.endpoint >pct_h.out &&
  	grep "^tcp" pct_h.out &&
  	test_must_fail grep "%h" pct_h.out
  
  lt-flux-broker: tcp://fe80::20d:3aff:fe9c:c5b26.953029e-310th0:*: No such device
  lt-flux-broker: overlay_bind failed: No such device
  lt-flux-broker: bootstrap failed
  flux-start: 0 (pid 10631) exited with rc=1
  flux-start: 1 (pid 10637) Killed
  not ok 29 - tbon.endpoint can be set and %h works
```

I was able to get a login to the GH Actions running for more information:

```
runner@fv-az276-779:/usr/src/t$ FLUX_TESTS_LOGFILE=t ASAN_OPTIONS=detect_leaks=0,start_deactivated=true LD_PRELOAD=/usr/lib64/libasan.so.6 TAP_DRIVER_QUIET=t FLUX_TEST_SIZE_MAX=4 ../src/cmd/flux start -s2 -vvv -o,--setattr=tbon.endpoint=tcp://%h:*
flux-start: 0: /usr/src/src/broker/flux-broker --setattr=rundir=/tmp/flux-1377-t8URFk --setattr=tbon.endpoint=ipc://%B/req --setattr=tbon.endpoint=tcp://%h:*
flux-start: 1: /usr/src/src/broker/flux-broker --setattr=rundir=/tmp/flux-1377-t8URFk --setattr=tbon.endpoint=ipc://%B/req --setattr=tbon.endpoint=tcp://%h:*
lt-flux-broker: tcp://fe80::20d:3aff:fef6:49b36.952543e-310th0:*: No such device
lt-flux-broker: overlay_bind failed: No such device
lt-flux-broker: bootstrap failed
flux-start: 0 (pid 1404) exited with rc=1
^Clt-flux-broker: broker_pmi_barrier: operation failed
```

A hint might be in the output of the `./test_ipaddr.t` unit test:
```
runner@fv-az16-763:/usr/src/src/common/libutil$ ./test_ipaddr.t 
ok 1 - ipaddr_getprimary works
# primary: fe80::20d:3aff:fe8d:ebec%eth0
ok 2 - ipaddrs_getall works
# 127.0.0.1
# 10.1.0.4
# 172.17.0.1
# ::1
# fe80::20d:3aff:fe8d:ebec%eth0
# fe80::42:dbff:fedb:f146%docker0
1..2
```

**Comment by grondo** [comment]
This may work to avoid expanding the endpoints unnecessarily (untested, trying out a build now)
```diff
diff --git a/src/broker/boot_config.c b/src/broker/boot_config.c
index 49d073792..80b416adc 100644
--- a/src/broker/boot_config.c
+++ b/src/broker/boot_config.c
@@ -471,7 +471,7 @@ int boot_config (flux_t *h, struct overlay *overlay, attr_t *attrs, int tbon_k)
                                        bind_uri,
                                        sizeof (bind_uri)) < 0)
             goto error;
-        if (overlay_set_child (overlay, bind_uri) < 0) {
+        if (overlay_set_child (overlay, "%s", bind_uri) < 0) {
             log_err ("overlay_set_child %s", bind_uri);
             goto error;
         }
@@ -513,7 +513,7 @@ int boot_config (flux_t *h, struct overlay *overlay, attr_t *attrs, int tbon_k)
                                       parent_uri,
                                       sizeof (parent_uri)) < 0)
             goto error;
-        if (overlay_set_parent (overlay, parent_uri) < 0) {
+        if (overlay_set_parent (overlay, "%s", parent_uri) < 0) {
             log_err ("overlay_set_parent %s", parent_uri);
             goto error;
         }
diff --git a/src/broker/boot_pmi.c b/src/broker/boot_pmi.c
index e45a0f78f..a80129b25 100644
--- a/src/broker/boot_pmi.c
+++ b/src/broker/boot_pmi.c
@@ -227,7 +227,7 @@ int boot_pmi (struct overlay *overlay, attr_t *attrs, int tbon_k)
             log_msg ("update_endpoint_attr failed");
             goto error;
         }
-        if (overlay_set_child (overlay, tbonendpoint) < 0) {
+        if (overlay_set_child (overlay, "%s", tbonendpoint) < 0) {
             log_err ("overlay_set_child");
             goto error;
         }


```

**Comment by grondo** [comment]
That appeared to fix the expansion of `%e` in the endpoint, but still getting an error:
```
 lt-flux-broker: tcp://fe80::20d:3aff:fe1a:9475%eth0:*: Invalid argument
```

Maybe zeromq doesn't support the ipv6 zone index? (Honestly, the `<addr>%<index>` address form is something new to me so I'm not quite sure how things should work here.)

**Comment by garlick** [comment]
Hmm, I haven't seen that before either, but I don't have any experience whatsoever with IPv6 addresses.

Looking around to see if this has been reported by libzmq communtiy, I did find this:

https://github.com/zeromq/pyzmq/issues/1226

Where an address like this `tcp://[fe80::3be:94a3:15be:2407%eth1]:5555` supposedly works as of libzmq-4.2.5.  I haven't been able find an issue/PR that describes what was broken and fixed.

**Comment by grondo** [comment]
Hm, that didn't work
```
runner@fv-az276-779:/usr/src$ rpm -q zeromq
zeromq-4.3.3-1.fc33.x86_64
runner@fv-az276-779:/usr/src$ src/cmd/flux start -s2 -o,--setattr=tbon.endpoint=fe80::20d:3aff:fefc:4169%eth0:*
lt-flux-broker: fe80::20d:3aff:fefc:4169%eth0:*: Invalid argument: Invalid argument
lt-flux-broker: overlay_bind failed: Invalid argument
lt-flux-broker: bootstrap failed
flux-start: 0 (pid 30530) exited with rc=1
^C
lt-flux-broker: broker_pmi_barrier: operation failed
lt-flux-broker: bootstrap failed
runner@fv-az276-779:/usr/src$ src/cmd/flux start -s2 -o,--setattr=tbon.endpoint=[fe80::20d:3aff:fefc:4169%eth0]:*
lt-flux-broker: [fe80::20d:3aff:fefc:4169%eth0]:*: Invalid argument: Invalid argument
lt-flux-broker: overlay_bind failed: Invalid argument
lt-flux-broker: bootstrap failed
flux-start: 0 (pid 30588) exited with rc=1
^Clt-flux-broker: broker_pmi_barrier: operation failed

runner@fv-az276-779:/usr/src$ lt-flux-broker: bootstrap failed

runner@fv-az276-779:/usr/src$ src/cmd/flux start -s2 -o,--setattr=tbon.endpoint=[fe80::20d:3aff:fefc:4169%eth0]:5555
lt-flux-broker: [fe80::20d:3aff:fefc:4169%eth0]:5555: Invalid argument: Invalid argument
lt-flux-broker: overlay_bind failed: Invalid argument
lt-flux-broker: bootstrap failed
flux-start: 0 (pid 30646) exited with rc=1
^Clt-flux-broker: broker_pmi_barrier: operation failed

```

In this branch I also added a call to `zsock_set_ipv6 (ep->zs, 1)` which I assume is necessary to bind zeromq to IPV6 addresses, but unfortunately that didn't seem to help either.

**Comment by grondo** [comment]
Can't get it to work with pyzmq either:
```
runner@fv-az54-679:/usr/src$ python3 t.py tcp://[fe80::20d:3aff:fe8e:2a29%eth0]:*
Traceback (most recent call last):
  File "/usr/src/t.py", line 8, in <module>
    socket.bind(f"{sys.argv[1]}:")
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Invalid argument
```

```python
runner@fv-az54-679:/usr/src$ cat t.py 
import time
import sys
import zmq

context = zmq.Context()
socket = context.socket(zmq.REP)
socket.bind(f"{sys.argv[1]}:")

while True:
    #  Wait for next request from client
    message = socket.recv()
    print("Received request: ", message)
    time.sleep (1)
    socket.send("World from %s" % port)
```

**Comment by garlick** [comment]
Hmm, makes me wonder if this was fix that was backported to several branches of libzmq, i.e. libzmq-4.2.5 is just the minimum version on the 4.2 series?

**Comment by grondo** [comment]
I've updated the issue description based on new understanding of this issue. (The problem with `%` expansion in ipv6 addresses has since been fixed.)

The issue seems to be that ipv6 link-local addresses can' t be used with zeromq, possibly as of zeromq-4.3.3. 

See also https://github.com/zeromq/libzmq/issues/4108

The problem is that for `bind(2)` to work on a link-local address, the `sin6_scope_id` must be correctly set to the index of the interface to which the link-local address belongs, e.g. for the following interface:

```
2: ens18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether f6:a1:0f:75:e5:cb brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.11/24 brd 192.168.1.255 scope global dynamic ens18
       valid_lft 5514sec preferred_lft 5514sec
    inet6 fe80::f4a1:fff:fe75:e5cb/64 scope link 
```

This bind call fails with `EINVAL`:

```
socket(AF_INET6, SOCK_STREAM, IPPROTO_IP) = 3
bind(3, {sa_family=AF_INET6, sin6_port=htons(0), sin6_flowinfo=htonl(0), 
        inet_pton(AF_INET6, "fe80::f4a1:fff:fe75:e5cb", &sin6_addr), 
        sin6_scope_id=0}, 28) = -1 EINVAL (Invalid argument)
```

Since the `scope_id` is set to 0. If we force the `scope_id` to 2, then the bind works:
```
bind(3, {sa_family=AF_INET6, sin6_port=htons(0), sin6_flowinfo=htonl(0),
        inet_pton(AF_INET6, "fe80::f4a1:fff:fe75:e5cb", &sin6_addr),
        sin6_scope_id=if_nametoindex("ens18")}, 28) = 0
```

The problem in the case here is two-fold:

 1. If the address expanded by `%h` is an ipv6 link-local address and is passed as-is to `zmq_bind()`, zeromq will not know to add a scope id, so unless the interface has a scope_id of `0`, bind will fail with `EINVAL`.
 2. Even if we add the interface scope to the address by appending `%ens18`, the referenced bug in zeromq-4.3.3 above causes `0` to always be returned from `if_nametoindex()`, so `bind` will fail.

Problem 1 can be worked around by adding the scope id to the returned address from `ipaddr_getprimary()` when the "primary" address appears to be an ipv6 link-local address (I guess in the range `fe80::/64`).

Problem 2 can be worked around by appending the numeric scope_id to the returned address instead of an interface name, e.g. in this case `fe80::f4a1:fff:fe75:e5cb%2`

```
$ src/cmd/flux start --wrap=libtool,e,strace,-e,bind -s2 -o,-Stbon.endpoint=tcp://fe80::f4a1:fff:fe75:e5cb%2:65535
bind(15, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 0
bind(15, {sa_family=AF_INET6, sin6_port=htons(65535), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "fe80::f4a1:fff:fe75:e5cb", &sin6_addr), sin6_scope_id=if_nametoindex("ens18")}, 28) = 0

```

**Comment by garlick** [comment]
I think this is solved?  Or at least, we fail early now.  Reopen if there is more to do.
