### ISSUE TITLE
python: interruptible decorator should be disabled when in reactor

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3432]
I was getting _very_ strange results with the interruptibility of Python commands while they were in the Flux reactor. Many of my existing scripts that I was certain used to work, stopped being interruptible with Ctrl-C.

After _lots_ of debugging, it turns out the problem occurs when a synchronous rpc or future `get()` is called from _within_ the reactor, i.e. from in a callback. This causes the `@interruptible` decorator to reset the signal state such that the `reactor_interrupted` handler for `SIGINT` does not get called. Instead a `KeyboardInterrupt` exception is thrown within whatever callback is entered next, and then ignored after we go back to sleep in the reactor.

This reproducer shows the effect:

```python
import sys
import flux
from flux.core.watchers import TimerWatcher

def timer_cb(handle, watcher, revents, _args):
    handle.reactor_stop()

def ping_cb(rpc, do_sync=False):
    print(rpc.get_str())
    if do_sync:
       print("synchronous ping in ping_cb:")
       print(rpc.get_flux().rpc("kvs.ping", {}).get_str())

do_sync = len(sys.argv) > 1 and sys.argv[1] == "sync" 

h = flux.Flux()

h.rpc("kvs.ping", {}).then(ping_cb, do_sync=do_sync)
TimerWatcher(h, 30, timer_cb).start()

h.reactor_run()
```

If called with `sync` the program is uninterruptible while sleeping in the reactor waiting for the TimerWatcher:
```
$ flux python t2.py sync
{"route": "60301c6c!7fcbee39!0!a8706a0e", "userid": 1000, "rolemask": 1}
synchronous ping in ping_cb:
{"route": "60301c6c!7fcbee39!0!a8706a0e", "userid": 1000, "rolemask": 1}
^C^C^\Quit (core dumped)
```

But if called without the synchronous `get()` in `ping_cb`, the program is interruptible:
```
$ flux python t2.py 
{"route": "ffc92469!7fcbee39!0!a8706a0e", "userid": 1000, "rolemask": 1}
^CTraceback (most recent call last):
  File "t2.py", line 21, in <module>
    h.reactor_run()
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/core/handle.py", line 204, in reactor_run
    raise KeyboardInterrupt
KeyboardInterrupt
```

To fix this, we may need a global, per-thread variable that indicates if the current thread is executing under the Flux reactor. This current approach _seems_ to be working for me, though I have no idea if it is the "right" approach or not:

```diff
diff --git a/src/bindings/python/flux/core/handle.py b/src/bindings/python/flux/
core/handle.py
index e95849129..b998c7020 100644
--- a/src/bindings/python/flux/core/handle.py
+++ b/src/bindings/python/flux/core/handle.py
@@ -10,6 +10,7 @@
 
 import signal
 import six
+import threading
 
 from flux.wrapper import Wrapper
 from flux.rpc import RPC
@@ -32,6 +33,11 @@ class Flux(Wrapper):
         <flux.core.Flux object at 0x...>
     """
 
+    #  Thread local storage so each thread can be marked as globally
+    #   running in the reactor or not.
+    tls = threading.local()
+    tls.reactor_running = False
+
     def __init__(self, url=ffi.NULL, flags=0, handle=None):
         super(Flux, self).__init__(
             ffi,
@@ -53,6 +59,19 @@ class Flux(Wrapper):
 
         self.aux_txn = None
 
+    @classmethod
+    def reactor_running(cls):
+        """Return True if this thread is running the Flux reactor"""
+        return cls.tls.reactor_running
+
+    @classmethod
+    def reactor_enter(cls):
+        cls.tls.reactor_running = True
+
+    @classmethod
+    def reactor_exit(cls):
+        cls.tls.reactor_running = False
+
     # pylint: disable=no-self-use
     def close(self):
         """
@@ -198,7 +217,9 @@ class Flux(Wrapper):
 
         with self.signal_watcher_create(signal.SIGINT, reactor_interrupt):
             self.reactor_active_decref(reactor)
+            Flux.reactor_enter()
             rc = self.flux_reactor_run(reactor, flags)
+            Flux.reactor_exit()
             self.reactor_active_incref(reactor)
             if reactor_interrupted:
                 raise KeyboardInterrupt
diff --git a/src/bindings/python/flux/util.py b/src/bindings/python/flux/util.py
index dbb99a0db..84b4ddd0e 100644
--- a/src/bindings/python/flux/util.py
+++ b/src/bindings/python/flux/util.py
@@ -57,18 +57,24 @@ def check_future_error(func):
 
 
 def interruptible(func):
-    """Make a method interruptible via Ctrl-C
+    """Make a Future method interruptible via Ctrl-C
 
-    Necessary for methods that may block when calling into the C API.
+    Necessary for Future methods that may block when calling into the C API.
     """
 
-    def func_wrapper(calling_obj, *args, **kwargs):
+    def func_wrapper(future, *args, **kwargs):
         # python only allows `signal.signal` calls in the main thread
-        if threading.current_thread() is threading.main_thread():
+        # only activate if the process is not in the Flux reactor
+        active = False
+        if (
+            threading.current_thread() is threading.main_thread()
+            and not type(future.get_flux()).reactor_running()
+        ):
             handler = signal.getsignal(signal.SIGINT)
             signal.signal(signal.SIGINT, signal.SIG_DFL)
-        retval = func(calling_obj, *args, **kwargs)
-        if threading.current_thread() is threading.main_thread():
+            active = True
+        retval = func(future, *args, **kwargs)
+        if active:
             signal.signal(signal.SIGINT, handler)
         return retval

```

**Comment by SteVwonder** [comment]
Thanks for tracking this down @grondo! This LGTM.
