### ISSUE TITLE
job-info doesn't track unset priority for jobs

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3475]
In the PRIORITY state, jobs do not yet have a priority assigned.

Currently, job-info doesn't track "unknown" or "unset" priority, so if any jobs are in the PRIORITY state (or a previous state, such as DEPEND?), job-info doesn't return a priority attribute even if requested, which generates an inscrutable error from flux-jobs:

```
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ flux jobs -ano {id},{priority}
flux-jobs: ERROR: 
```

The reproducer is most easily generated with job manager plugin support (#3464). The "test.so" plugin holds all submitted jobs in PRIORITY state for 30s to show the results:

```
 grondo@asp:~/git/f.git$ src/cmd/flux start
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ flux jobtap load ./test.so
builtin.default
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ flux mini submit hostname
ƒ8UYSyjd
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ flux jobs
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME NODELIST
    ƒ8UYSyjd grondo   hostname   PD      1      -        - -
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ flux jobs -ano {id},{priority}
flux-jobs: ERROR: 
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ FLUX_HANDLE_TRACE=1 FLUX_PYCLI_LOGLEVEL=10 flux jobs -ano {id},{priority}
--------------------------------------
>[000] ||
>[013] job-info.list
>[099] {"max_entries": 1000, "attrs": ["result", "priority"], "userid": 1000, "states": 126, "results": 0}
>[020] 8E01010BFFFFFFFF00000000FFFFFFFF00000001
--------------------------------------
<[000] ||
<[013] job-info.list
<[055] {"jobs":[{"id":284558360576,"result":1,"priority":16}]}
<[020] 8E01020B000003E8000000010000000000000001
ƒ8UYSyjd,16
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ exit
exit
 grondo@asp:~/git/f.git$ src/cmd/flux start
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ flux mini submit hostname
ƒ3532rNK
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ flux jobs
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME NODELIST
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ exit
exit
 grondo@asp:~/git/f.git$ src/cmd/flux start
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ flux jobtap load test.so
builtin.default
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ flux mini submit hostname
ƒ9xJPSCX
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ flux jobs
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME NODELIST
    ƒ9xJPSCX grondo   hostname   PD      1      -        - -
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ FLUX_HANDLE_TRACE=1 FLUX_PYCLI_LOGLEVEL=10 flux jobs -ano {id},{priority}
--------------------------------------
>[000] ||
>[013] job-info.list
>[099] {"max_entries": 1000, "attrs": ["result", "priority"], "userid": 1000, "states": 126, "results": 0}
>[020] 8E01010BFFFFFFFF00000000FFFFFFFF00000001
--------------------------------------
<[000] ||
<[013] job-info.list
<[030] {"jobs":[{"id":340845920256}]}
<[020] 8E01020B000003E8000000010000000000000001
flux-jobs: ERROR: 
flux-jobs: DEBUG: Traceback (most recent call last):
  File "/home/grondo/git/f.git/src/bindings/python/flux/util.py", line 164, in __call__
    main_func()
  File "/home/grondo/git/f.git/src/cmd/flux-jobs.py", line 324, in main
    print(formatter.format(job))
  File "/home/grondo/git/f.git/src/bindings/python/flux/job/info.py", line 415, in format
    return self.JobFormatter().format(self.get_format(), obj)
  File "/usr/lib/python3.6/string.py", line 190, in format
    return self.vformat(format_string, args, kwargs)
  File "/usr/lib/python3.6/string.py", line 194, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/usr/lib/python3.6/string.py", line 234, in _vformat
    obj, arg_used = self.get_field(field_name, args, kwargs)
  File "/usr/lib/python3.6/string.py", line 305, in get_field
    obj = getattr(obj, i)
  File "/home/grondo/git/f.git/src/bindings/python/flux/job/info.py", line 157, in __getattr__
    return getattr(self, "_{0}".format(attr))
  File "/home/grondo/git/f.git/src/bindings/python/flux/job/info.py", line 155, in __getattr__
    raise AttributeError
AttributeError

```

**Comment by chu11** [comment]
ahh good catch.  We're not handling the "no priority returned" case similar to fields like `nnodes` or `t_inactive`, which depend on if a job is in a certain state yet.  Fix would mostly likely be in the `JobInfo`  class.

**Comment by grondo** [comment]
Ah, ok. Good hint!

**Comment by grondo** [comment]
Ha, that's one-liner, thanks:
```diff
diff --git a/src/bindings/python/flux/job/info.py b/src/bindings/python/flux/job
/info.py
index 0feb9e5a7..5830768c8 100644
--- a/src/bindings/python/flux/job/info.py
+++ b/src/bindings/python/flux/job/info.py
@@ -106,6 +106,7 @@ class JobInfo:
         "t_inactive": 0.0,
         "expiration": 0.0,
         "nnodes": "",
+        "priority": "",
         "ranks": "",
         "nodelist": "",
         "success": "",
```
