### ISSUE TITLE
flux resource drain/undrain should work from any rank

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3483]
Small oversight here:
```
$ flux start -s2
$ flux exec -r 1 flux resource drain 1
flux-resource: ERROR: [Errno 38] Unknown service method
1: Exit 1
$ flux exec -r 1 flux resource undrain 1
flux-resource: ERROR: [Errno 38] Unknown service method
1: Exit 1
```
A system administrator should probably be able to run these commands on any node.

**Comment by grondo** [comment]
Good catch! `flux resource status` seems to have the same problem, but also causes a local broker segfault :sob: 

```console
$ flux start -s 2 flux exec -r 1 flux resource status
flux-start: 1 (pid 7260) Segmentation fault
```

```
Program terminated with signal 11, Segmentation fault.
#0  exclude_get (exclude=0x0) at exclude.c:41
41	    return exclude->idset;
Missing separate debuginfos, use: debuginfo-install czmq-3.0.2-3.el7.x86_64 hwloc-libs-1.11.8-4.el7.x86_64 jansson-2.10-1.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-50.1chaos.ch6.x86_64 libcom_err-1.42.9-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libselinux-2.5-15.el7.x86_64 libsodium-1.0.18-1.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 libtool-ltdl-2.4.2-22.el7_3.x86_64 libuuid-2.23.2-65.el7.x86_64 munge-libs-0.5.14-1.ch6.x86_64 numactl-libs-2.0.12-5.el7.x86_64 openpgm-5.2.122-2.el7.x86_64 pcre-8.32-17.el7.x86_64 zeromq-4.1.5-3.ch6.x86_64
(gdb) where
#0  exclude_get (exclude=0x0) at exclude.c:41
#1  0x00002aaac0421c78 in status_cb (h=0x2aaac8001130, mh=<optimized out>, 
    msg=0x2aaac800d120, arg=0x2aaac800ba00) at resource.c:161
#2  0x00002aaaaacec434 in call_handler (mh=0x2aaac800c090, 
    msg=msg@entry=0x2aaac800d120) at msg_handler.c:231
#3  0x00002aaaaacecb69 in dispatch_message (type=1, msg=0x2aaac800d120, 
    d=0x2aaac800acd0) at msg_handler.c:267
#4  handle_cb (r=0x2aaac800a4a0, hw=<optimized out>, revents=<optimized out>, 
    arg=0x2aaac800acd0) at msg_handler.c:367
#5  0x00002aaaaad12f55 in ev_invoke_pending (loop=0x2aaac800a4c0) at ev.c:3372
#6  0x00002aaaaad16aa7 in ev_run (loop=0x2aaac800a4c0, flags=0) at ev.c:3775
#7  0x00002aaaaaceb5c3 in flux_reactor_run (r=0x2aaac800a4a0, 
    flags=flags@entry=0) at reactor.c:126
#8  0x00002aaac042220d in mod_main (h=0x2aaac8001130, argc=<optimized out>, 
    argv=<optimized out>) at resource.c:418
#9  0x000000000040b2fc in module_thread (arg=0x662f00) at module.c:214
#10 0x00002aaaab87cea5 in start_thread (arg=0x2aaac0eb9700)
    at pthread_create.c:307
#11 0x00002aaaac50296d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

```
