### ISSUE TITLE
t3302-system-offline.t fails in the rpm buildfarm

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3760]
```
flux-mini: ERROR: [Errno 22] sign-munge-sign: Failed to access "/run/munge/munge.socket.2": No such file or directory
flux-mini: DEBUG: Traceback (most recent call last):
  File "/builddir/build/BUILD/flux-core-0.28.0/src/bindings/python/flux/util.py", line 201, in __call__
    main_func()
  File "/builddir/build/BUILD/flux-core-0.28.0/src/cmd/flux-mini.py", line 1615, in main
    args.func(args)
  File "/builddir/build/BUILD/flux-core-0.28.0/src/cmd/flux-mini.py", line 1321, in main
    jobid = self.submit(args)
  File "/builddir/build/BUILD/flux-core-0.28.0/src/cmd/flux-mini.py", line 673, in submit
    return JobID(self.submit_async(args, jobspec).get_id())
  File "/builddir/build/BUILD/flux-core-0.28.0/src/bindings/python/flux/job/submit.py", line 22, in get_id
    return submit_get_id(self)
  File "/builddir/build/BUILD/flux-core-0.28.0/src/bindings/python/flux/util.py", line 53, in func_wrapper
    raise EnvironmentError(error.errno, errmsg.decode("utf-8")) from None
OSError: [Errno 22] sign-munge-sign: Failed to access "/run/munge/munge.socket.2
```

**Comment by garlick** [comment]
Normally munge signing of job requests is bypassed when the submitting user is the same as the instance owner.  It determines this by making a getattr request on `security.owner`.  In this test, the broker is not connected to its upstream peer and rejects the getattr request, and the submit code falls back to signing the request.  However, in the buildfarm munge is not running so this fails.

One idea is to use SO_PEERCRED to determine the instance owner on the other end of the socket.  This would probably be a bit less overhead too, since getting the attribute incurs a message round-trip delay.

**Comment by grondo** [comment]
To reproduce, stop the `munge` service and rerun the test by hand (flux-core must be configured `--with-flux-security`):
```
$ ./t3302-system-offline.t -d -v
sharness: loading extensions from /home/grondo/git/f.git/t/sharness.d/01-setup.sh
sharness: loading extensions from /home/grondo/git/f.git/t/sharness.d/flux-sharness.sh
sharness: loading extensions from /home/grondo/git/f.git/t/sharness.d/01-setup.sh
sharness: loading extensions from /home/grondo/git/f.git/t/sharness.d/flux-sharness.sh
expecting success: 
	$startctl run 2

ok 1 - start rank 2 before TBON parent is up

expecting success: 
        test $($startctl status | jq -r ".procs[1].pid") = "-1"

ok 2 - startctl shows rank 1 pid as -1

expecting success: 
	test_must_fail bash -c \
		"FLUX_URI=$(echo $FLUX_URI | sed s/local-0/local-2/) \
			flux mini run hostname" 2>online.err &&
	test_debug "cat online.err" &&
	grep "broker is offline" online.err

flux-mini: ERROR: [Errno 22] sign-munge-sign: Failed to access "/var/run/munge/munge.socket.2": No such file or directory
flux-mini: DEBUG: Traceback (most recent call last):
  File "/home/grondo/git/f.git/src/bindings/python/flux/util.py", line 201, in __call__
    main_func()
  File "/home/grondo/git/f.git/src/cmd/flux-mini.py", line 1615, in main
    args.func(args)
  File "/home/grondo/git/f.git/src/cmd/flux-mini.py", line 1321, in main
    jobid = self.submit(args)
  File "/home/grondo/git/f.git/src/cmd/flux-mini.py", line 673, in submit
    return JobID(self.submit_async(args, jobspec).get_id())
  File "/home/grondo/git/f.git/src/bindings/python/flux/job/submit.py", line 22, in get_id
    return submit_get_id(self)
  File "/home/grondo/git/f.git/src/bindings/python/flux/util.py", line 53, in func_wrapper
    raise EnvironmentError(error.errno, errmsg.decode("utf-8")) from None
OSError: [Errno 22] sign-munge-sign: Failed to access "/var/run/munge/munge.socket.2": No such file or directory

not ok 3 - flux mini run on rank 2 fails with offline error
#	
#		test_must_fail bash -c \
#			"FLUX_URI=$(echo $FLUX_URI | sed s/local-0/local-2/) \
#				flux mini run hostname" 2>online.err &&
#		test_debug "cat online.err" &&
#		grep "broker is offline" online.err
#	

# failed 1 among 3 test(s)
1..3
2021-07-01T15:09:10.526037Z broker.err[0]: rc2.0: /bin/bash -c sh ./t3302-system-offline.t  --verbose --debug --root=/home/grondo/git/f.git/t/trash-directory.t3302-system-offline Exited (rc=1) 0.9s
flux-start: 0 (pid 5770) exited with rc=1
flux-start: 2 (pid 6356) Killed
```

I patched the test to display the output of `flux mini run hostname`
```diff
diff --git a/t/t3302-system-offline.t b/t/t3302-system-offline.t
index 596eaef4f..b2dc5026e 100755
--- a/t/t3302-system-offline.t
+++ b/t/t3302-system-offline.t
@@ -25,6 +25,7 @@ test_expect_success 'flux mini run on rank 2 fails with offline error' '
        test_must_fail bash -c \
                "FLUX_URI=$(echo $FLUX_URI | sed s/local-0/local-2/) \
                        flux mini run hostname" 2>online.err &&
+       test_debug "cat online.err" &&
        grep "broker is offline" online.err
 '
 
```

**Comment by grondo** [comment]
Here's a change that seems to workaround the signing issue, but still tests that detection of offline upstream broker works. I could perhaps apply this patch to the specfile, though I think @garlick's suggestion above is a better long term fix:
```diff
diff --git a/t/t3302-system-offline.t b/t/t3302-system-offline.t
index 596eaef4f..5c6d082e4 100755
--- a/t/t3302-system-offline.t
+++ b/t/t3302-system-offline.t
@@ -22,9 +22,13 @@ test_expect_success HAVE_JQ 'startctl shows rank 1 pid as -1' '
 '
 
 test_expect_success 'flux mini run on rank 2 fails with offline error' '
+       flux mini run --dry-run hostname > job.json &&
+       flux python ${SHARNESS_TEST_SRCDIR}/scripts/sign-as.py \
+               $(id -u) job.json >J &&
        test_must_fail bash -c \
                "FLUX_URI=$(echo $FLUX_URI | sed s/local-0/local-2/) \
-                       flux mini run hostname" 2>online.err &&
+                       flux job submit --flags=signed J" 2>online.err &&
+       test_debug "cat online.err" &&
        grep "broker is offline" online.err
 '

```
