### ISSUE TITLE
flux --parent has wrong FLUX_EXEC_PATH when grandparent is system instance

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4038]
`t2802-uri-cmd.t` currently fails when run as a job in a system instance:

```
expecting success: 
	jobid2=$(flux jobs -no {user.jobid} $jobid) &&
	test_debug "echo attempting to resolve jobid:${jobid}/${jobid2}" &&
	uri=$(FLUX_SSH=$testssh flux uri --local jobid:${jobid}/${jobid2}) &&
	test_debug "echo jobid:${jobid}/${jobid2} is ${uri}" &&
	uri=$(FLUX_SSH=$testssh flux uri --local ${jobid}/${jobid2}) &&
	test_debug "echo ${jobid}/${jobid2} is ${uri}"

attempting to resolve jobid:f3vhcnvK/fP1ULdu
hostname=fluke26
cmd="LD_LIBRARY_PATH=/usr/lib64/flux /g/g0/grondo/git/flux-core.git/src/cmd/flux relay /var/tmp/grondo/flux-PWkMjy/local-0"
flux-uri: ERROR: [Errno 38] No service matching job-list.list-id is registered
flux-uri: DEBUG: Traceback (most recent call last):
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/util.py", line 203, in __call__
    main_func()
  File "/g/g0/grondo/git/flux-core.git/src/cmd/flux-uri.py", line 57, in main
    uri = resolver.resolve(args.uri)
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/uri/uri.py", line 192, in resolve
    result = JobURI(self.resolvers[scheme].resolve(resolver_uri))
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/uri/resolvers/jobid.py", line 72, in resolve
    return self._do_resolve(uri, flux.Flux(), force_local=force_local)
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/uri/resolvers/jobid.py", line 64, in _do_resolve
    resolver_uri, flux.Flux(uri), force_local=force_local
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/uri/resolvers/jobid.py", line 45, in _do_resolve
    flux_handle, jobid, attrs=["state", "annotations"]
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/job/list.py", line 94, in get_jobinfo
    return JobInfo(self.get_job())
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/job/list.py", line 91, in get_job
    return self.get()["job"]
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/rpc.py", line 78, in get
    resp_str = self.get_str()
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/util.py", line 79, in func_wrapper
    retval = func(future, *args, **kwargs)
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/rpc.py", line 72, in get_str
    self.pimpl.flux_rpc_get(payload_str)
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/wrapper.py", line 347, in wrap_class
    return new_fun(self_renamed, *args, **kwargs)
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/util.py", line 55, in func_wrapper
    raise EnvironmentError(error.errno, errmsg.decode("utf-8")) from None
OSError: [Errno 38] No service matching job-list.list-id is registered

not ok 14 - flux uri resolves hierarchical jobid argument
#	
#		jobid2=$(flux jobs -no {user.jobid} $jobid) &&
#		test_debug "echo attempting to resolve jobid:${jobid}/${jobid2}" &&
#		uri=$(FLUX_SSH=$testssh flux uri --local jobid:${jobid}/${jobid2}) &&
#		test_debug "echo jobid:${jobid}/${jobid2} is ${uri}" &&
#		uri=$(FLUX_SSH=$testssh flux uri --local ${jobid}/${jobid2}) &&
#		test_debug "echo ${jobid}/${jobid2} is ${uri}"
#	

expecting success: 
	test_debug "echo attempting to resolve jobid:${jobid}/${jobid2}" &&
	uri=$(flux uri jobid:${jobid}/${jobid2}?local) &&
	test_debug "echo jobid:${jobid}/${jobid2}?local is ${uri}" &&
	uri=$(flux uri ${jobid}/${jobid2}?local) &&
	test_debug "echo ${jobid}/${jobid2}?local is ${uri}"


attempting to resolve jobid:f3vhcnvK/fP1ULdu
flux-uri: ERROR: [Errno 38] No service matching job-list.list-id is registered
flux-uri: DEBUG: Traceback (most recent call last):
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/util.py", line 203, in __call__
    main_func()
  File "/g/g0/grondo/git/flux-core.git/src/cmd/flux-uri.py", line 57, in main
    uri = resolver.resolve(args.uri)
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/uri/uri.py", line 192, in resolve
    result = JobURI(self.resolvers[scheme].resolve(resolver_uri))
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/uri/resolvers/jobid.py", line 72, in resolve
    return self._do_resolve(uri, flux.Flux(), force_local=force_local)
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/uri/resolvers/jobid.py", line 64, in _do_resolve
    resolver_uri, flux.Flux(uri), force_local=force_local
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/uri/resolvers/jobid.py", line 45, in _do_resolve
    flux_handle, jobid, attrs=["state", "annotations"]
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/job/list.py", line 94, in get_jobinfo
    return JobInfo(self.get_job())
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/job/list.py", line 91, in get_job
    return self.get()["job"]
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/rpc.py", line 78, in get
    resp_str = self.get_str()
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/util.py", line 79, in func_wrapper
    retval = func(future, *args, **kwargs)
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/rpc.py", line 72, in get_str
    self.pimpl.flux_rpc_get(payload_str)
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/wrapper.py", line 347, in wrap_class
    return new_fun(self_renamed, *args, **kwargs)
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/util.py", line 55, in func_wrapper
    raise EnvironmentError(error.errno, errmsg.decode("utf-8")) from None
OSError: [Errno 38] No service matching job-list.list-id is registered

not ok 15 - flux uri resolves hierarchical jobids with ?local
#	
#		test_debug "echo attempting to resolve jobid:${jobid}/${jobid2}" &&
#		uri=$(flux uri jobid:${jobid}/${jobid2}?local) &&
#		test_debug "echo jobid:${jobid}/${jobid2}?local is ${uri}" &&
#		uri=$(flux uri ${jobid}/${jobid2}?local) &&
#		test_debug "echo ${jobid}/${jobid2}?local is ${uri}"
#	
#	
```

I ran this down to the fact that the test job was segfaulting when running `flux job --parent memo`:

```console
$ cat trash-directory.t2802-uri-cmd/flux-f3vhcnvK.out 
/var/tmp/grondo/flux-script-111383937024-UbwrVo: line 4: 645787 Illegal instruction     (core dumped) flux --parent job memo $(flux getattr jobid) jobid=$jobid
2022-01-08T19:11:06.285398Z broker.err[0]: rc2.0: /bin/bash -c /var/tmp/grondo/flux-script-111383937024-UbwrVo Exited (rc=132) 0.5s
2022-01-08T19:11:06.473894Z broker.err[0]: cleanup.1: flux-job: Canceled 1 jobs (0 errors)
```

The problem here is that `flux --parent job memo .. ` was somehow picking up the system `flux-job` instead of the build directory.

I ran this down to `environment_push()` in `push_parent_environment()`. What is occurring is that when `environment_push()` pushes a colon-separated list of entries instead of a single entry, it does so in the wrong order, since the  list is traversed in order and each entry is pushed onto the front.  This ends up placing the system cmd-path first on FLUX_EXEC_PATH, when it was the _last_ entry on the parent's FLUX_EXEC_PATH.

**Comment by grondo** [comment]
I had a simple fix proposed in #4039, but the fixed cause `make distcheck` and vpath builds to fail.

It turns out that the problem was that, once the order of paths pushed onto `PYTHONPATH` was fixed, the resulting environment made it so that python was unable to `import flux` in a vpath build, because it couldn't find the `_flux._core` module.

I'm not sure why this would be, because the build directory was definitely in the resulting `PYTHONPATH`, it just moved to 2nd slot instead of the first. Changing the builddir to the first position instead fixes the problem, though I don't really understand why. My only assumption is a python bug.
