### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections'

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4040]
```
Traceback (most recent call last):
  File "/home/ben/Shared/Work/test/flux-x86_64/libexec/flux/cmd/flux-mini.py", line 28, in <module>
    from flux import job
  File "/home/ben/Shared/Work/test/flux-x86_64/lib/flux/python3.10/flux/job/__init__.py", line 16, in <module>
    from flux.job.info import JobInfo, JobInfoFormat
  File "/home/ben/Shared/Work/test/flux-x86_64/lib/flux/python3.10/flux/job/info.py", line 23, in <module>
    from flux.resource import SchedResourceList
  File "/home/ben/Shared/Work/test/flux-x86_64/lib/flux/python3.10/flux/resource/__init__.py", line 11, in <module>
    from flux.resource.Rlist import Rlist
  File "/home/ben/Shared/Work/test/flux-x86_64/lib/flux/python3.10/flux/resource/Rlist.py", line 13, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)
```

A quick google seems to indicate that it should be `from collections.abc import Mapping`

**Comment by woodard** [comment]
changing those two lines to "from collections.abc import Mapping" seems to have fixed the problem.
