### ISSUE TITLE
flux mini run fails on Spack built flux-sched

### ISSUE THREAD

**Issue by wkharold** [flux-framework/flux-core#4285]
Built flux-sched on CentOS 7 with Spack 0.17.1

running ```flux mini run -n4 --label-io hostname``` failed with

    2022-04-13T16:46:43.100676Z job-ingest.err[0]: validator[0]: exited with rc=1
    flux-mini: ERROR: [Errno 71] Unrecoverable error: validator unexpectedly exited

It failed after a Slurm `salloc` and after `flux start --test-size=4`

**Comment by grondo** [comment]
Ok, I rebuilt flux-core on the 0.17.1 branch and was not able to reproduce the problem. 

Here's the output of `spack spec flux-core` on my system.

```
$ spack spec flux-core
Input spec
--------------------------------
flux-core

Concretized
--------------------------------
flux-core@0.30.0%gcc@11.2.0~cuda~docs patches=0329f4b38b5ce4e1a3dee212cb93ce40388d1bde47c82a7a8e73bc7c38274c81 arch=linux-rhel7-broadwell
    ^czmq@4.1.1%gcc@11.2.0 arch=linux-rhel7-broadwell
        ^autoconf@2.69%gcc@11.2.0 patches=35c449281546376449766f92d49fc121ca50e330e60fefcfc9be2af3253082c2,7793209b33013dc0f81208718c68440c5aae80e7a1c4b8d336e382525af791a7,a49dd5bac3b62daa0ff688ab4d508d71dbd2f4f8d7e2a02321926346161bf3ee arch=linux-rhel7-broadwell
            ^m4@1.4.19%gcc@11.2.0+sigsegv patches=9dc5fbd0d5cb1037ab1e6d0ecc74a30df218d0a94bdd5a02759a97f62daca573,bfdffa7c2eb01021d5849b36972c069693654ad826c1a20b53534009a4ec7a89 arch=linux-rhel7-broadwell
                ^libsigsegv@2.13%gcc@11.2.0 arch=linux-rhel7-broadwell
            ^perl@5.34.0%gcc@11.2.0+cpanm+shared+threads arch=linux-rhel7-broadwell
                ^berkeley-db@18.1.40%gcc@11.2.0+cxx~docs+stl patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=linux-rhel7-broadwell
                ^bzip2@1.0.8%gcc@11.2.0~debug~pic+shared arch=linux-rhel7-broadwell
                    ^diffutils@3.8%gcc@11.2.0 arch=linux-rhel7-broadwell
                        ^libiconv@1.16%gcc@11.2.0 libs=shared,static arch=linux-rhel7-broadwell
                ^gdbm@1.19%gcc@11.2.0 arch=linux-rhel7-broadwell
                    ^readline@8.1%gcc@11.2.0 arch=linux-rhel7-broadwell
                        ^ncurses@6.2%gcc@11.2.0~symlinks+termlib abi=none arch=linux-rhel7-broadwell
                            ^pkgconf@1.8.0%gcc@11.2.0 arch=linux-rhel7-broadwell
                ^zlib@1.2.11%gcc@11.2.0+optimize+pic+shared arch=linux-rhel7-broadwell
        ^automake@1.16.3%gcc@11.2.0 arch=linux-rhel7-broadwell
        ^libtool@2.4.6%gcc@11.2.0 arch=linux-rhel7-broadwell
        ^libzmq@4.3.3%gcc@11.2.0~drafts+libsodium patches=8ebde83ee148989f9118d36ebaf256532627b8a6e7a486842110623331972edb arch=linux-rhel7-broadwell
            ^libbsd@0.11.3%gcc@11.2.0 arch=linux-rhel7-broadwell
                ^libmd@1.0.3%gcc@11.2.0 arch=linux-rhel7-broadwell
            ^libsodium@1.0.18%gcc@11.2.0 arch=linux-rhel7-broadwell
        ^util-linux-uuid@2.36.2%gcc@11.2.0 arch=linux-rhel7-broadwell
    ^hwloc@2.6.0%gcc@11.2.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~opencl+pci~rocm+shared arch=linux-rhel7-broadwell
        ^libpciaccess@0.16%gcc@11.2.0 arch=linux-rhel7-broadwell
            ^util-macros@1.19.3%gcc@11.2.0 arch=linux-rhel7-broadwell
        ^libxml2@2.9.12%gcc@11.2.0~python arch=linux-rhel7-broadwell
            ^xz@5.2.5%gcc@11.2.0~pic libs=shared,static arch=linux-rhel7-broadwell
    ^jansson@2.13.1%gcc@11.2.0~ipo+shared build_type=RelWithDebInfo arch=linux-rhel7-broadwell
        ^cmake@3.21.4%gcc@11.2.0~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-rhel7-broadwell
            ^openssl@1.1.1l%gcc@11.2.0~docs certs=system arch=linux-rhel7-broadwell
    ^lua@5.3.5%gcc@11.2.0~pcfile+shared arch=linux-rhel7-broadwell
        ^unzip@6.0%gcc@11.2.0 arch=linux-rhel7-broadwell
    ^lua-luaposix@35.0%gcc@11.2.0 arch=linux-rhel7-broadwell
    ^lz4@1.9.3%gcc@11.2.0 libs=shared,static arch=linux-rhel7-broadwell
    ^py-cffi@1.15.0%gcc@11.2.0 arch=linux-rhel7-broadwell
        ^libffi@3.3%gcc@11.2.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=linux-rhel7-broadwell
        ^py-pycparser@2.20%gcc@11.2.0 arch=linux-rhel7-broadwell
            ^py-setuptools@58.2.0%gcc@11.2.0 arch=linux-rhel7-broadwell
                ^python@3.8.12%gcc@11.2.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87,4c2457325f2b608b1b6a2c63087df8c26e07db3e3d493caf36a56f0ecf6fb768,f2fd060afc4b4618fe8104c4c5d771f36dc55b1db5a4623785a4ea707ec72fb4 arch=linux-rhel7-broadwell
                    ^expat@2.4.1%gcc@11.2.0+libbsd arch=linux-rhel7-broadwell
                    ^gettext@0.21%gcc@11.2.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-rhel7-broadwell
                        ^tar@1.34%gcc@11.2.0 arch=linux-rhel7-broadwell
                    ^sqlite@3.36.0%gcc@11.2.0+column_metadata+fts~functions~rtree arch=linux-rhel7-broadwell
    ^py-jsonschema@3.2.0%gcc@11.2.0 arch=linux-rhel7-broadwell
        ^py-attrs@21.2.0%gcc@11.2.0 arch=linux-rhel7-broadwell
        ^py-pyrsistent@0.15.7%gcc@11.2.0 arch=linux-rhel7-broadwell
            ^py-six@1.16.0%gcc@11.2.0 arch=linux-rhel7-broadwell
        ^py-setuptools-scm@6.3.2%gcc@11.2.0+toml arch=linux-rhel7-broadwell
            ^py-packaging@21.0%gcc@11.2.0 arch=linux-rhel7-broadwell
                ^py-pyparsing@2.4.7%gcc@11.2.0 arch=linux-rhel7-broadwell
            ^py-tomli@1.2.1%gcc@11.2.0 arch=linux-rhel7-broadwell
                ^py-pip@21.1.2%gcc@11.2.0 arch=linux-rhel7-broadwell
    ^py-pyyaml@5.3.1%gcc@11.2.0+libyaml arch=linux-rhel7-broadwell
        ^libyaml@0.2.5%gcc@11.2.0 arch=linux-rhel7-broadwell
    ^yaml-cpp@0.7.0%gcc@11.2.0~ipo+pic+shared~tests build_type=RelWithDebInfo arch=linux-rhel7-broadwell
```


At first I thought maybe things were working for me because we have `flux-core` installed on the system, so perhaps the spack version was finding the system installed plugins. So I added some debug to the `jobspec.py` validator plugin to verify it was the one being loaded:

```console
$ flux mini run --dry-run hostname | flux job-validator --jobspec-only 
hello from jobspec validator
{"errnum": 0}
```

Other things we can try:

  * after running `spack load flux-core`, then try this command:
    ```console
    $ flux python -c 'import flux.job.validator.plugins.jobspec as j; print(j)'
    <module 'flux.job.validator.plugins.jobspec' from '/p/vast1/grondo/spack/opt/spack/linux-rhel7-broadwell/gcc-11.2.0/flux-core-0.30.0-xykzfbsozzjulwcv6vffmirbp4ys2svu/lib/flux/python3.8/flux/job/validator/plugins/jobspec.py'>
    ```
    Note that the full path to the validator plugin should be displayed in the the output. If the module fails to import, then could you share the output of `echo $PYTHONPATH | tr ':' '\n'`? We can see if somehow the PYTHONPATH is not correct.

  * If the above works, then try `flux job-validator --list-plugins` and ensure you have something like:
    ```console
    $ flux job-validator --list-plugins
    Available plugins:
    feasibility           Use sched.feasibility RPC to validate job
    jobspec               Python bindings based jobspec validator
    schema                Validate jobspec using jsonschema
    ```

**Comment by wkharold** [comment]
Thanks for looking into this. Here's what I've got:

### Fix up the module path to find Spack installed things
```$ export MODULEPATH=$MODULEPATH:/sw/spack/share/spack/modules/linux-centos7-cascadelake:/sw/spack/share/spack/modules/linux-centos7-x86_64```

### Load flux-core
```
$ module load py-pyyaml
$ module load flux-core
```
It seems odd that I have to explicitly load `py-pyyaml`; I don't recall having to do that on Rocky

### See if the validator plugin is there
```
$ flux python -c 'import flux.job.validator.plugins.jobspec as j; print(j)'
<module 'flux.job.validator.plugins.jobspec' from '/sw/spack/opt/spack/linux-centos7-cascadelake/gcc-10.3.0/flux-core-master-jobhovyngogyyh6nkxejqfu32o2nv6io/lib/flux/python3.8/flux/job/validator/plugins/jobspec.py'>
```
Seems OK

### PYTHONPATH for completeness
```
$ echo $PYTHONPATH | tr ':' '\n'
/sw/spack/opt/spack/linux-centos7-cascadelake/gcc-10.3.0/flux-core-master-jobhovyngogyyh6nkxejqfu32o2nv6io/lib/python3.8/site-packages
/sw/spack/opt/spack/linux-centos7-cascadelake/gcc-10.3.0/py-six-1.16.0-tucy6hpxn6vaguvmbv7kmuv23pxvl4j7/lib/python3.8/site-packages
/sw/spack/opt/spack/linux-centos7-cascadelake/gcc-10.3.0/py-pycparser-2.20-zqncqupedg4uggyzdsnxzkinctueiexy/lib/python3.8/site-packages
/sw/spack/opt/spack/linux-centos7-cascadelake/gcc-10.3.0/py-cffi-1.15.0-qy5s5c7xsvy7ay4s5ex7jrez3k7ydczv/lib/python3.8/site-packages
/sw/spack/opt/spack/linux-centos7-cascadelake/gcc-10.3.0/py-pyyaml-5.3.1-ag3pa4ulfpbk2z7ib6k35awxsqgsqrfe/lib/python3.8/site-packages
```
### Unable to list plugins
```
$ flux job-validator --list-plugins
Available plugins:
flux-job-validator: ERROR: 'list' object has no attribute 'items'
```

**Comment by wkharold** [comment]
Also, `spack spec flux-core` output for completeness

```
$ /sw/spack/bin/spack spec flux-core
Input spec
--------------------------------
flux-core

Concretized
--------------------------------
==> Bootstrapping clingo from pre-built binaries
flux-core@0.30.0%gcc@10.3.0~cuda~docs patches=0329f4b38b5ce4e1a3dee212cb93ce40388d1bde47c82a7a8e73bc7c38274c81 arch=linux-centos7-cascadelake
    ^czmq@4.1.1%gcc@10.3.0 arch=linux-centos7-cascadelake
        ^autoconf@2.69%gcc@10.3.0 patches=35c449281546376449766f92d49fc121ca50e330e60fefcfc9be2af3253082c2,7793209b33013dc0f81208718c68440c5aae80e7a1c4b8d336e382525af791a7,a49dd5bac3b62daa0ff688ab4d508d71dbd2f4f8d7e2a02321926346161bf3ee arch=linux-centos7-cascadelake
            ^m4@1.4.19%gcc@10.3.0+sigsegv patches=9dc5fbd0d5cb1037ab1e6d0ecc74a30df218d0a94bdd5a02759a97f62daca573,bfdffa7c2eb01021d5849b36972c069693654ad826c1a20b53534009a4ec7a89 arch=linux-centos7-cascadelake
                ^libsigsegv@2.13%gcc@10.3.0 arch=linux-centos7-cascadelake
            ^perl@5.34.0%gcc@10.3.0+cpanm+shared+threads arch=linux-centos7-cascadelake
                ^berkeley-db@18.1.40%gcc@10.3.0+cxx~docs+stl patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=linux-centos7-cascadelake
                ^bzip2@1.0.8%gcc@10.3.0~debug~pic+shared arch=linux-centos7-cascadelake
                    ^diffutils@3.8%gcc@10.3.0 arch=linux-centos7-cascadelake
                        ^libiconv@1.16%gcc@10.3.0 libs=shared,static arch=linux-centos7-cascadelake
                ^gdbm@1.19%gcc@10.3.0 arch=linux-centos7-cascadelake
                    ^readline@8.1%gcc@10.3.0 arch=linux-centos7-cascadelake
                        ^ncurses@6.2%gcc@10.3.0~symlinks+termlib abi=none arch=linux-centos7-cascadelake
                            ^pkgconf@1.8.0%gcc@10.3.0 arch=linux-centos7-cascadelake
                ^zlib@1.2.11%gcc@10.3.0+optimize+pic+shared arch=linux-centos7-cascadelake
        ^automake@1.16.3%gcc@10.3.0 arch=linux-centos7-cascadelake
        ^libtool@2.4.6%gcc@10.3.0 arch=linux-centos7-cascadelake
        ^libzmq@4.3.3%gcc@10.3.0~drafts+libsodium arch=linux-centos7-cascadelake
            ^libbsd@0.11.3%gcc@10.3.0 arch=linux-centos7-cascadelake
                ^libmd@1.0.3%gcc@10.3.0 arch=linux-centos7-cascadelake
            ^libsodium@1.0.18%gcc@10.3.0 arch=linux-centos7-cascadelake
        ^util-linux-uuid@2.36.2%gcc@10.3.0 arch=linux-centos7-cascadelake
    ^hwloc@2.6.0%gcc@10.3.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~opencl+pci~rocm+shared arch=linux-centos7-cascadelake
        ^libpciaccess@0.16%gcc@10.3.0 arch=linux-centos7-cascadelake
            ^util-macros@1.19.3%gcc@10.3.0 arch=linux-centos7-cascadelake
        ^libxml2@2.9.12%gcc@10.3.0~python arch=linux-centos7-cascadelake
            ^xz@5.2.5%gcc@10.3.0~pic libs=shared,static arch=linux-centos7-cascadelake
    ^jansson@2.13.1%gcc@10.3.0~ipo+shared build_type=RelWithDebInfo arch=linux-centos7-cascadelake
        ^cmake@3.21.4%gcc@10.3.0~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-centos7-cascadelake
            ^openssl@1.1.1l%gcc@10.3.0~docs certs=system arch=linux-centos7-cascadelake
    ^lua@5.3.5%gcc@10.3.0~pcfile+shared arch=linux-centos7-cascadelake
        ^unzip@6.0%gcc@10.3.0 arch=linux-centos7-cascadelake
    ^lua-luaposix@35.0%gcc@10.3.0 arch=linux-centos7-cascadelake
    ^lz4@1.9.3%gcc@10.3.0 libs=shared,static arch=linux-centos7-cascadelake
    ^py-cffi@1.15.0%gcc@10.3.0 arch=linux-centos7-cascadelake
        ^libffi@3.3%gcc@10.3.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=linux-centos7-cascadelake
        ^py-pycparser@2.20%gcc@10.3.0 arch=linux-centos7-cascadelake
            ^py-setuptools@58.2.0%gcc@10.3.0 arch=linux-centos7-cascadelake
                ^python@3.8.12%gcc@10.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87,4c2457325f2b608b1b6a2c63087df8c26e07db3e3d493caf36a56f0ecf6fb768,f2fd060afc4b4618fe8104c4c5d771f36dc55b1db5a4623785a4ea707ec72fb4 arch=linux-centos7-cascadelake
                    ^expat@2.4.1%gcc@10.3.0+libbsd arch=linux-centos7-cascadelake
                    ^gettext@0.21%gcc@10.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos7-cascadelake
                        ^tar@1.34%gcc@10.3.0 arch=linux-centos7-cascadelake
                    ^sqlite@3.36.0%gcc@10.3.0+column_metadata+fts~functions~rtree arch=linux-centos7-cascadelake
    ^py-jsonschema@3.2.0%gcc@10.3.0 arch=linux-centos7-cascadelake
        ^py-attrs@21.2.0%gcc@10.3.0 arch=linux-centos7-cascadelake
        ^py-pyrsistent@0.15.7%gcc@10.3.0 arch=linux-centos7-cascadelake
            ^py-six@1.16.0%gcc@10.3.0 arch=linux-centos7-cascadelake
        ^py-setuptools-scm@6.3.2%gcc@10.3.0+toml arch=linux-centos7-cascadelake
            ^py-packaging@21.0%gcc@10.3.0 arch=linux-centos7-cascadelake
                ^py-pyparsing@2.4.7%gcc@10.3.0 arch=linux-centos7-cascadelake
            ^py-tomli@1.2.1%gcc@10.3.0 arch=linux-centos7-cascadelake
                ^py-pip@21.1.2%gcc@10.3.0 arch=linux-centos7-cascadelake
    ^py-pyyaml@5.3.1%gcc@10.3.0+libyaml arch=linux-centos7-cascadelake
        ^libyaml@0.2.5%gcc@10.3.0 arch=linux-centos7-cascadelake
    ^yaml-cpp@0.7.0%gcc@10.3.0~ipo+pic+shared~tests build_type=RelWithDebInfo arch=linux-centos7-cascadelake
```

**Comment by grondo** [comment]
> It seems odd that I have to explicitly load py-pyyaml; I don't recall having to do that on Rocky

Yeah, that shouldn't be required. However, I'm not a spack expert TBH. I usually use `spack load` instead of `module load` but I'm assuming the former is just a thin wrapper around the latter? In any event, I'll double check that the dependency is properly specified in the `package.py`.

> Unable to list plugins
> ```
> $ flux job-validator --list-plugins
> Available plugins:
> flux-job-validator: ERROR: 'list' object has no attribute 'items'
> ```

Sorry, I forgot to request one other thing when running this command, can you set `FLUX_PYCLI_LOGLEVEL=10` before running `flux job-validator --list-plugins`? I'm a little mystified when the validator fails when the plugins do seem to be found in `PYTHONPATH`, but I don't quite understand this error, and the above environment variable will let Python dump the entire backtrace.

Thanks!

**Comment by grondo** [comment]
> It seems odd that I have to explicitly load py-pyyaml; I don't recall having to do that on Rocky

Ah, maybe because of this:
```python
    depends_on("py-pyyaml")
```
Actually pyyaml isn't required as a build dependency but is a run only dependency. There are probably other similar problems in the flux-core `package.py`. I wonder if it might work on another system because there's a compatible version of pyyaml installed on the system?

**Comment by wkharold** [comment]
Here's the `flux job-validator --list-plugins` output with `FLUX_PYCLI_LOGLEVEL=10`:

```
$ flux job-validator --list-plugins
Available plugins:
flux-job-validator: ERROR: 'list' object has no attribute 'items'
flux-job-validator: DEBUG: Traceback (most recent call last):
  File "/sw/spack/opt/spack/linux-centos7-cascadelake/gcc-10.3.0/flux-core-master-jobhovyngogyyh6nkxejqfu32o2nv6io/lib/flux/python3.8/flux/util.py", line 205, in __call__
    main_func()
  File "/sw/spack/opt/spack/linux-centos7-cascadelake/gcc-10.3.0/flux-core-master-jobhovyngogyyh6nkxejqfu32o2nv6io/libexec/flux/cmd/flux-job-validator.py", line 74, in main
    for name, plugin in validator.plugins.items():
AttributeError: 'list' object has no attribute 'items'
```
My Python fu is not strong but it seems as if it's not getting the 'list' object it expects.

**Comment by grondo** [comment]
Ah, thanks! I have to check, but I think the problem is that the script expects `validator.plugins` to be a `dict`, but it is a `list`. I'm a little mystified since this works everywhere else, but I have a couple ideas, and at least I know where to look now.

I may have to ask you to try a patch if I can't reproduce here.

**Comment by wkharold** [comment]
OK. I stumbled onto the solution: `module load jsonschema`

If you either a) load py-pip and install jsonschema or b) load py-jsonschema everything works as expected.

I'll have to check and see what Python modules Rocky has installed by default. Maybe that's why I didn't have to do any of this in that environment.

Regardless, we can close this. Really appreciate your help!

**Comment by grondo** [comment]
Ah! Yeah we have jsonschema locally which was shadowing this issue. I think our spack packaging is not quite doing the right thing for all Python dependencies, so I'm going to try to fix that (once I figure out what the right thing is).

Also, your full stack trace above helped me find an actual bug in the code! If no plugins are found, an empty `list` is returned instead of an empty `dict`!

Thanks for helping us solve this problem! :+1:
