### ISSUE TITLE
broker: segfault during t0014-runlevel.t 'rc3 failure causes instance failure' test

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4564]
Problem: consistent broker segfault in `t0014-runlevel.t` after upgrading development system to Ubuntu 22.04 (gcc 11.2.0)

Specifically this test:
```
test_expect_success 'rc3 failure causes instance failure' '
        test_expect_code 1 flux start \
                -o,-Sbroker.rc3_path=/bin/false \
                -o,-Slog-stderr-level=6 \
                /bin/true 2>rc3_failure.log
'
```
Here's a backtrace:
```
Thread 1 "flux-broker-0" received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
74	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) bt -full
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
No locals.
#1  0x00007ffff7f4f400 in flux_msg_route_push (msg=msg@entry=0x5555555d8850, 
    id=0x5550000af83d <error: Cannot access memory at address 0x5550000af83d>) at message.c:737
No locals.
#2  0x00005555555670bf in module_sendmsg (msg=<optimized out>, p=0x5555555fdb00) at module.c:312
        type = 1
        topic = 0x5555555f3230 "job-manager.disconnect"
        cpy = 0x5555555d8850
        rc = <optimized out>
        cpy = <optimized out>
        type = <optimized out>
        topic = <optimized out>
        rc = <optimized out>
        done = <optimized out>
#3  module_sendmsg (p=0x5555555fdb00, msg=<optimized out>) at module.c:287
        cpy = 0x0
        type = <optimized out>
        topic = <optimized out>
        rc = -1
        done = <optimized out>
#4  0x000055555556c4b5 in service_send (sw=0x5555555be7d0, msg=msg@entry=0x5555555f3380) at service.c:220
        topic = 0x5555555f3230 "job-manager.disconnect"
        p = <optimized out>
        length = <optimized out>
        svc = 0x5555555fab50
#5  0x0000555555563ef8 in broker_request_sendmsg_internal (ctx=ctx@entry=0x7fffffffd400, msg=msg@entry=0x5555555f3380)
    at broker.c:1805
        nodeid = 4294967295
        flags = 13 '\r'
#6  0x000055555556530c in broker_request_sendmsg (msg=0x5555555f3380, ctx=0x7fffffffd400) at broker.c:1836
        topic = <optimized out>
        errbuf = <optimized out>
        errstr = <optimized out>
#7  disconnect_send_cb (msg=0x5555555f3380, arg=0x7fffffffd400) at broker.c:1619
        ctx = 0x7fffffffd400
#8  0x000055555558979f in disconnect_fire (dcon=0x555555604c50) at disconnect.c:194
        msg = <optimized out>
#9  disconnect_destroy (dcon=0x555555604c50) at disconnect.c:204
        saved_errno = 11
#10 disconnect_destroy (dcon=0x555555604c50) at disconnect.c:201
        saved_errno = <optimized out>
        saved_errno = <optimized out>
        saved_errno = <optimized out>
#11 0x0000555555566cfc in module_destroy (p=0x5555556087d0) at module.c:386
        e = <optimized out>
        res = 0xffffffffffffffff
        saved_errno = <optimized out>
#12 0x000055555558c622 in s_item_destroy (self=self@entry=0x5555555bdf70, item=0x555555609740, hard=hard@entry=true)
    at zhash.c:136
        cur_item = <optimized out>
        prev_item = <optimized out>
        __PRETTY_FUNCTION__ = "s_item_destroy"
#13 0x000055555558c834 in fzhash_destroy (self_p=self_p@entry=0x5555555bdf20) at zhash.c:100
--Type <RET> for more, q to quit, c to continue without paging--
        next_item = 0x0
        cur_item = <optimized out>
        self = <optimized out>
        index = 136
        __PRETTY_FUNCTION__ = "fzhash_destroy"
#14 0x00005555555679a0 in modhash_destroy (mh=0x5555555bdf20) at module.c:677
        saved_errno = 11
        uuid = <optimized out>
        p = 0x0
        e = <optimized out>
#15 0x0000555555563043 in main (argc=<optimized out>, argv=<optimized out>) at broker.c:534
        ctx = {h = 0x5555555c2b30, reactor = 0x5555555c2750, opts = 0x5555555c0460, overlay = 0x5555555c4c20, rank = 0, 
          size = 1, online = true, starttime = 1662921592.9486806, attrs = 0x5555555bf050, cred = {userid = 5588, 
            rolemask = 1}, modhash = 0x5555555bdf20, verbose = 0, event_recv_seq = 6, sigwatchers = 0x5555555bdee0, 
          services = 0x5555555be7d0, config = 0x5555555c2d60, heartbeat_rate = 0, subscriptions = 0x5555555bf8d0, 
          cache = 0x5555555d3060, publisher = 0x5555555c6150, groups = 0x5555555cadf0, runat = 0x5555555cb4e0, 
          state_machine = 0x5555555d45c0, shutdown = 0x5555555d5790, init_shell_cmd = 0x5555555c1b70 "/bin/true", 
          init_shell_cmd_len = 10, exit_rc = 1}
        old_sigmask = {__val = {0, 140737353880008, 2954611200, 140737353879960, 140737488344928, 140737353934825, 
            140737488344387, 140737488345408, 140737488344384, 1024, 140737471604326, 140737353933692, 140737351931152, 
            140737347865296, 0, 18446742974197923840}}
        old_sigact_int = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 140737488344064, 
              140737488344064, 93824992680768, 93824992485949, 2, 3, 93824992680784, 93824992303092, 93824992669776, 
              140737488346328, 93824992486101, 140737488344960, 140737488344432, 15385369633798454016, 140737488346328}}, 
          sa_flags = 0, sa_restorer = 0x0}
        old_sigact_term = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 
              140737488344064, 140737488344064, 93824992680768, 93824992485949, 2, 3, 93824992680784, 93824992303092, 
              93824992669776, 140737488346328, 93824992486101, 140737488344960, 140737488344432, 15385369633798454016, 
              140737488346328}}, sa_flags = 0, sa_restorer = 0x0}
        handlers = 0x5555555d2370
        conf = <optimized out>
        sigmask = {__val = {18446744066168191815, 72340168526266367, 5931345451726490695, 6872211854156977737, 95, 0, 
            7955995191841808741, 7813308248005571689, 3480, 0, 96, 0, 140737350111376, 140737350113136, 140737350108752, 
            140737350110064}}
        __PRETTY_FUNCTION__ = "main"
        flags = 1
(gdb) 
```

**Comment by grondo** [comment]
Is this a duplicate of #4280?

**Comment by garlick** [comment]
It is indeed!  Thanks for pointing that out.  I'll close this one.
