### ISSUE TITLE
testsuite: do not assume "/usr/bin/env python3" equates to "flux python"

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#5091]
Recently hit an issue in the testsuite on corona getting a lot of errors like:

```
Traceback (most recent call last):
  File "/g/g0/achu/chaos/git/flux-framework/flux-core/t/scripts/dmesg-grep.py", line 18, in <module>
    import flux
  File "/g/g0/achu/chaos/git/flux-framework/flux-core/src/bindings/python/flux/__init__.py", line 14, in <module>
    import flux.core.handle
  File "/g/g0/achu/chaos/git/flux-framework/flux-core/src/bindings/python/flux/core/handle.py", line 15, in <module>
    from _flux._core import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'
```

The issue was that I built / configured `flux python` to be Python 3.6 (i.e. `PYTHON_VERSION=3.6` during configuration).  By some dumb chance, a `python3.7` existed in `/usr/local/bin/python3` which was earlier in my path than `/usr/bin/python3`.  So scripts that did `/usr/bin/env python3` were picking up a different version of python and leading to errors.

I think instead of `/usr/bin/env python3` we should probably be doing `/usr/bin/env -S flux python`.  Not for installed scripts, but atleast within the python scripts in the testsuite.

**Comment by chu11** [comment]
As an aside, in another chat @grondo suggested doing something like:

```
PATH=$(flux python -c 'import os,sys; print(os.path.dirname(sys.executable))'):$PATH
```

in `t/sharness.d/01-setup.sh`.  I gave it a shot but suddenly realized, when `01-setup.sh` is sourced, a test flux instance may not yet be setup, so `flux python` will lead to an error.  There's ways to get around this, but figured just doing `/usr/bin/env -S flux python` might be the safer / correct route.

Or perhaps there's another better way.

**Comment by grondo** [comment]
The PATH is set to the correct flux executable first (otherwise flux start wouldn't work). I tried my suggestion and it worked for the conda build.

One problem I think we ran into with the other solution is that many times the shebang only supports at most two arguments (iirc). If you search back in old issues you might find a very long thread about this problem...

**Comment by chu11** [comment]
Ahhh I think I just had to be slightly less stupid:

```Python
diff --git a/t/sharness.d/01-setup.sh b/t/sharness.d/01-setup.sh
index 84b02f97f..05e1b2630 100644
--- a/t/sharness.d/01-setup.sh
+++ b/t/sharness.d/01-setup.sh
@@ -44,11 +44,9 @@ fi
 #  Add path to flux(1) command to PATH
 #
 if test -n "$FLUX_TEST_INSTALLED_PATH"; then
-    PATH=$FLUX_TEST_INSTALLED_PATH:$PATH
-    fluxbin=$FLUX_TEST_INSTALLED_PATH/flux
+    fluxpath=$FLUX_TEST_INSTALLED_PATH
 else # normal case, use ${top_builddir}/src/cmd/flux
-    PATH=$FLUX_BUILD_DIR/src/cmd:$PATH
-    fluxbin=$FLUX_BUILD_DIR/src/cmd/flux
+    fluxpath=$FLUX_BUILD_DIR/src/cmd
 
     #  Ensure that the built libflux-*.so are found before any system
     #   installed versions. This is necessary because sometimes libtool
@@ -57,6 +55,9 @@ else # normal case, use ${top_builddir}/src/cmd/flux
     #
     export LD_LIBRARY_PATH="${FLUX_BUILD_DIR}/src/common/.libs:$LD_LIBRARY_PATH"
 fi
+fluxbin=${fluxpath}/flux
+fluxpythonpath=`${fluxbin} python -c 'import os,sys; print(os.path.dirname(sys.executable))'`
+PATH=${fluxpath}:${fluxpythonpath}:$PATH
 export PATH

```

on corona there is a flux and python3 in `/usr/bin`.  So multiple dumb ways could grab the wrong python3 or the wrong flux.

> One problem I think we ran into with the other solution is that many times the shebang only supports at most two arguments (iirc). If you search back in old issues you might find a very long thread about this problem...

Yeah, I did `/usr/bin/env -S flux python` which is what the manpage said, but no idea how portable that is.

**Comment by chu11** [comment]
I just realized, the `01-setup.sh` approach won't work generically, b/c it assumes `python3` will always point to whatever flux the developer has configured.  if I configure PYTHON_VERSION=3.8 on corona, tests would fail.  But unfortunately ...

> Yeah, I did /usr/bin/env -S flux python which is what the manpage said, but no idea how portable that is.

Not portable, won't work on RHEL7.

hmm

**Comment by grondo** [comment]
I ended up with this in the conda patch:

```diff
diff --git a/t/sharness.d/01-setup.sh b/t/sharness.d/01-setup.sh
index 84b02f97f..2af287414 100644
--- a/t/sharness.d/01-setup.sh
+++ b/t/sharness.d/01-setup.sh
@@ -47,6 +47,8 @@ if test -n "$FLUX_TEST_INSTALLED_PATH"; then
     PATH=$FLUX_TEST_INSTALLED_PATH:$PATH
     fluxbin=$FLUX_TEST_INSTALLED_PATH/flux
 else # normal case, use ${top_builddir}/src/cmd/flux
+    PATH=$($FLUX_BUILD_DIR/src/cmd/flux python -c \
+           'import os,sys; print(os.path.dirname(sys.executable))'):$PATH
     PATH=$FLUX_BUILD_DIR/src/cmd:$PATH
     fluxbin=$FLUX_BUILD_DIR/src/cmd/flux
```

Since the path to `flux python` is prepended first, then `src/cmd` I think this would work in all situations, though I might be missing something. This patch also avoids mucking with TEST_INSTALL to keep it simpler.

**Comment by chu11** [comment]
> place flux-python or fluxpython in src/cmd and use #!/usr/bin/env fluxpython in test scripts 

because this is test specific, I was thinking it could be `flux-test-python` and we stick it in `t/scripts` or something like that.

Yeah, I can workaround my environment for the time being.  I recall my builds on corona working before, so my suspicion is python3.7 was put into /usr/local/bin at some point as users were ramping up on the system.

I do think that `/usr/bin/env -S flux python` is probably the correct long term solution, as it will deal with (AFAICT) most of the corner cases.  Perhaps in a few years when its more portable / we don't care about older distros :P

**Comment by chu11** [comment]
Correct me if I'm wrong, but if I configure PYTHON_VERSION=3.8 at build time, that (normally) gets `/usr/bin/python3.8`.  But `/usr/bin/python3` could still point to some other python?

I believe RHEL8 comes with Python 3.6 and 3.8, defaulting to 3.6 with `/usr/bin/python3`.  So I think it's a reasonable scenario that could be a problem?

**Comment by grondo** [comment]
Yes, you are correct I'd forgotten about different versions in the same directory. The patch does fix the case in things like conda where different python installations have different paths, so it resolves part of the problem, but not the issue you bring up here :thinking:
