### ISSUE TITLE
Python 3.11 support for flux-core

### ISSUE THREAD

**Issue by jan-janssen** [flux-framework/flux-core#5154]
As part of the conda-forge package, I took a look at the python 3.11 support. The compilation works fine, but the tests fail: 
https://github.com/conda-forge/flux-core-feedstock/pull/20

```
2023-05-04T09:34:17.2044439Z FAIL: t2241-queue-cmd-list.t 22 - flux-queue list accepts configured formats
2023-05-04T09:34:17.2045488Z ERROR: t2241-queue-cmd-list.t - exited with status 1
2023-05-04T09:39:11.0377032Z FAIL: t2352-resource-cmd-config.t 5 - flux-resource list accepts configured formats
2023-05-04T09:39:11.0377514Z FAIL: t2352-resource-cmd-config.t 6 - flux-resource status accepts configured formats
2023-05-04T09:39:11.0377990Z FAIL: t2352-resource-cmd-config.t 7 - flux-resource drain accepts configured formats
2023-05-04T09:39:11.0378452Z FAIL: t2352-resource-cmd-config.t 8 - flux-resource invalid key in subtable raises error
2023-05-04T09:39:11.0378888Z FAIL: t2352-resource-cmd-config.t 9 - flux-resource invalid config key raises error
2023-05-04T09:39:11.0379302Z ERROR: t2352-resource-cmd-config.t - exited with status 1
2023-05-04T09:49:13.0834680Z FAIL: t2800-jobs-config.t 4 - Additional formats can be added to XDG_CONFIG_HOME
2023-05-04T09:49:13.0839830Z FAIL: t2800-jobs-config.t 7 - flux-jobs config may omit description
2023-05-04T09:49:13.0841189Z FAIL: t2800-jobs-config.t 9 - XDG_CONFIG_DIRS can be colon-separated paths
2023-05-04T09:49:13.0841830Z FAIL: t2800-jobs-config.t 10 - Invalid flux-jobs config file causes meaningful error
2023-05-04T09:49:13.0842471Z FAIL: t2800-jobs-config.t 11 - flux-jobs does not allow internal formats to be overridden
2023-05-04T09:49:13.0843088Z FAIL: t2800-jobs-config.t 12 - flux-jobs checks that formats is a mapping
2023-05-04T09:49:13.0843674Z FAIL: t2800-jobs-config.t 13 - flux-jobs checks that formats.NAME is a mapping
2023-05-04T09:49:13.0844307Z FAIL: t2800-jobs-config.t 14 - flux-jobs checks that formats.NAME.format is a string
2023-05-04T09:49:13.0844925Z FAIL: t2800-jobs-config.t 15 - Invalid flux-jobs invalid config causes meaningful error
2023-05-04T09:49:13.0845466Z ERROR: t2800-jobs-config.t - exited with status 1
2023-05-04T09:52:22.1053399Z FAIL: t2811-flux-pgrep.t 16 - flux-pgrep reads flux-jobs formats configuration
2023-05-04T09:52:22.1053882Z ERROR: t2811-flux-pgrep.t - exited with status 1
```

The same tests work fine for Python 3.8 to 3.10 .

**Comment by grondo** [comment]
This is the error we're getting. Python 3.11 has its own tomllib
```
flux-pgrep: ERROR: File must be opened in binary mode, e.g. use `open('foo.toml', 'rb')`
flux-pgrep: DEBUG: Traceback (most recent call last):
  File "/usr/src/src/bindings/python/flux/util.py", line 216, in __call__
    main_func()
  File "/usr/src/src/cmd/flux-pgrep.py", line 258, in main
    fmt = FluxPgrepConfig().load().get_format_string(args.format)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/src/bindings/python/flux/util.py", line 1046, in load
    conf = self.extension_handlers[ppath.suffix](ofile)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/tomllib/_parser.py", line 63, in load
    raise TypeError(
TypeError: File must be opened in binary mode, e.g. use `open('foo.toml', 'rb')`
```

Interesting, I guess TOML files have to opened in binary mode:

https://github.com/hukkin/tomli#parse-a-toml-file

> The file must be opened in binary mode (with the "rb" flag). Binary mode will enforce decoding the file as UTF-8 with universal newlines disabled, both of which are required to correctly parse TOML.

This seems to fix the problem
```diff
diff --git a/src/bindings/python/flux/util.py b/src/bindings/python/flux/util.py
index f82226374..befc950b4 100644
--- a/src/bindings/python/flux/util.py
+++ b/src/bindings/python/flux/util.py
@@ -1042,7 +1042,7 @@ class UtilConfig:
                     continue
 
                 try:
-                    with open(filepath) as ofile:
+                    with open(filepath, "rb") as ofile:
                         conf = self.extension_handlers[ppath.suffix](ofile)
                 except (
                     tomllib.TOMLDecodeError,
```

**Comment by jan-janssen** [comment]
@grondo Thanks a lot - the patch solved the issue and I was able to update the conda-forge package to python 3.11
