### ISSUE TITLE
python: kvs still assumes all KVS values must be json

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#5198]
Per comments in #5037 and #5196.  json assumption was largely removed like in 2016 or something.  Since most users use the  "job" python API, this issue has lingered in the Python KVS functions for ages.

Example from #5196:

```
import flux
import flux.kvs

f = flux.Flux()
d = flux.kvs.KVSDir(f)

print(d['a']['b']['c'])
```

```
>flux kvs put a.b.c=foo
>flux python ./test.py
Traceback (most recent call last):
  File "./test.py", line 7, in <module>
    print(d['a']['b']['c'])
  File "/g/g0/achu/chaos/git/flux-framework/flux-core/src/bindings/python/flux/kvs.py", line 175, in __getitem__
    return get(self.fhdl, self.key_at(key))
  File "/g/g0/achu/chaos/git/flux-framework/flux-core/src/bindings/python/flux/kvs.py", line 71, in get
    return get_key_direct(flux_handle, key)
  File "/g/g0/achu/chaos/git/flux-framework/flux-core/src/bindings/python/flux/kvs.py", line 38, in get_key_direct
    ret = json.loads(ffi.string(valp[0]).decode("utf-8"))
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

>flux kvs put a.b.c=\"foo\"
>flux python test.py
foo
```

**Comment by chu11** [comment]
I tried the dumbest thing I could think of:

```
diff --git a/src/bindings/python/flux/kvs.py b/src/bindings/python/flux/kvs.py
index 377fd1c..dc6b30d 100644
--- a/src/bindings/python/flux/kvs.py
+++ b/src/bindings/python/flux/kvs.py
@@ -35,7 +35,7 @@ def get_key_direct(flux_handle, key):
     if valp[0] == ffi.NULL:
         return None
 
-    ret = json.loads(ffi.string(valp[0]).decode("utf-8"))
+    ret = ffi.string(valp[0]).decode("utf-8")
     RAW.flux_future_destroy(future)
     return ret
```

The failures in the tests were like:

```
FAIL: python/t0005-kvs.py 6 __main__.TestKVS.test_fill
  ---
    message: |
      Traceback (most recent call last):
        File "./python/t0005-kvs.py", line 94, in test_fill
          self.assertEqual(kd["things"], 1)
      AssertionError: '1' != 1
  ...
```

i.e. there are typing issues that `json.loads()` previously handled.  So then I tried the second stupidest thing I could think of:

```Python
diff --git a/src/bindings/python/flux/kvs.py b/src/bindings/python/flux/kvs.py
index 377fd1c..6e47400 100644
--- a/src/bindings/python/flux/kvs.py
+++ b/src/bindings/python/flux/kvs.py
@@ -35,7 +35,10 @@ def get_key_direct(flux_handle, key):
     if valp[0] == ffi.NULL:
         return None
 
-    ret = json.loads(ffi.string(valp[0]).decode("utf-8"))
+    try:
+        ret = json.loads(ffi.string(valp[0]).decode("utf-8"))
+    except json.decoder.JSONDecodeError:
+        ret = ffi.string(valp[0]).decode("utf-8")
     RAW.flux_future_destroy(future)
     return ret
```

And all tests pass (should add more of course) ... and I might need to handle a few other corner cases (like empty "no value" comes to mind).

To me this seems reasonable.  If it can't be decoded by json.loads(), just assume its a string??  Obviously there's some corner cases here, like if the user were to write binary data.  But this seems an acceptable compromise?  Should also handle the case I hit in #5037.

**Comment by grondo** [comment]
This makes sense to me!

> if the returned data can't be decoded in utf-8 perhaps should return bytesarray or similar?

Good thought. I think `ffi.string` returns `bytes`, so I'd just return that  result directly on `UnicodeDecodeError`.

**Comment by chu11** [comment]
Doh, and there's a `json.dumps()` on the other side of this too.

```
def put(flux_handle, key, value):                                                                                                           
    json_str = json.dumps(value)                                                                                                            
    if flux_handle.aux_txn is None:                                                                                                         
        flux_handle.aux_txn = RAW.flux_kvs_txn_create()                                                                                     
    return RAW.flux_kvs_txn_put(flux_handle.aux_txn, 0, key, json_str)
```
