### ISSUE TITLE
KeyError raised from assumption that `os.environ['PATH']` is always non-null

### ISSUE THREAD

**Issue by wihobbs** [flux-framework/flux-core#5562]
Getting an error where the `PATH` key value can't be retrieved from `flux run`:

```
[hobbs17@corona171:mpihello]$ FLUX_PYCLI_LOGLEVEL=10 python3 ./mpi_tests_v2.py 
stderr: jobid: f64Dp6MSF
stderr: flux-run: ERROR: 'PATH'
stderr: flux-run: DEBUG: Traceback (most recent call last):
stderr:   File "/usr/lib64/flux/python3.6/flux/util.py", line 279, in __call__
stderr:     main_func()
stderr:   File "/usr/libexec/flux/cmd/flux-run.py", line 37, in main
stderr:     args.func(args)
stderr:   File "/usr/lib64/flux/python3.6/flux/cli/run.py", line 75, in main
stderr:     os.environ["PATH"] = os.environ["FLUX_EXEC_PATH"] + ":" + os.environ["PATH"]
stderr:   File "/usr/lib64/python3.6/os.py", line 669, in __getitem__
stderr:     raise KeyError(key) from None
stderr: KeyError: 'PATH'
stderr: 
stderr: jobid: f64HykLg7
stderr: flux-run: ERROR: 'PATH'
stderr: flux-run: DEBUG: Traceback (most recent call last):
stderr:   File "/usr/lib64/flux/python3.6/flux/util.py", line 279, in __call__
stderr:     main_func()
stderr:   File "/usr/libexec/flux/cmd/flux-run.py", line 37, in main
stderr:     args.func(args)
stderr:   File "/usr/lib64/flux/python3.6/flux/cli/run.py", line 75, in main
stderr:     os.environ["PATH"] = os.environ["FLUX_EXEC_PATH"] + ":" + os.environ["PATH"]
stderr:   File "/usr/lib64/python3.6/os.py", line 669, in __getitem__
stderr:     raise KeyError(key) from None
stderr: KeyError: 'PATH'
stderr: 
```

FWIW, this is raised from a python script creating and submitting jobspecs for running a shell script. (I put the debug call in both the python call and the `flux run` down in the script`. In the script, using echo commands:

```
stdout: PATH=/usr/local/bin:/usr/bin
stdout: FLUX_EXEC_PATH=
```

**Comment by grondo** [comment]
Thanks! There's an assumption that `PATH` is always defined in `os.environ`. That should be fixed.
