### ISSUE TITLE
Fix Sanitizer issues with Lua

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#725]
Initially reported in Issue #694. For example, Lua doesn't like TSan-built dynamic module:

```
not ok 3 - lalarm: is function
#     Failed test (./lua/t0007-alarm.t at line 6)
#     error loading module 'lalarm' from file '/g/g0/dahn/workspace/Flux/flux-core/src/bindings/lua/.libs/lalarm.so':
#   /g/g0/dahn/workspace/Flux/flux-core/src/bindings/lua/.libs/lalarm.so: undefined symbol: __tsan_init isn't a 'function' it's a 'string'
/usr/bin/lua: ./lua/t0007-alarm.t:9: attempt to call local 'alarm' (a string value)
stack traceback:
    ./lua/t0007-alarm.t:9: in main chunk
    [C]: ?
FAIL: lua/t0007-alarm.t
```

**Comment by dongahn** [comment]
Also, AddressSanitizer cause coproc tests to crash. (Probably due to lack of makecontext/swapcontext support).

```
ok 14 - coproc_resume on returned coproc fails with EINVAL
ASAN:SIGSEGV
=================================================================
==132562==ERROR: AddressSanitizer: SEGV on unknown address 0x2aaab200b000 (pc 0x000000421ca8 bp 0x2aaab200b000 sp 0x7ffffffe95e0 T0)
    #0 0x421ca7 in __asan::AsanChunk::UsedSize(bool) /collab/usr/global/tools/clang/chaos_5_x86_64_ib/clang-omp-3.5.0/src/llvm-3.5.0.src/projects/compiler-rt/lib/asan/asan_allocator2.cc:157
    #1 0x421ca7 in QuarantineChunk /collab/usr/global/tools/clang/chaos_5_x86_64_ib/clang-omp-3.5.0/src/llvm-3.5.0.src/projects/compiler-rt/lib/asan/asan_allocator2.cc:447
    #2 0x421ca7 in Deallocate /collab/usr/global/tools/clang/chaos_5_x86_64_ib/clang-omp-3.5.0/src/llvm-3.5.0.src/projects/compiler-rt/lib/asan/asan_allocator2.cc:476
    #3 0x421ca7 in __asan::asan_free(void*, __sanitizer::StackTrace*, __asan::AllocType) /collab/usr/global/tools/clang/chaos_5_x86_64_ib/clang-omp-3.5.0/src/llvm-3.5.0.src/projects/compiler-rt/lib/asan/asan_allocator2.cc:598
    #4 0x4977ce in free /collab/usr/global/tools/clang/chaos_5_x86_64_ib/clang-omp-3.5.0/src/llvm-3.5.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:31
    #5 0x4b7ee9 in coproc_destroy /g/g0/dahn/workspace/Flux/flux-core/src/common/libutil/coproc.c:74:13
    #6 0x4b6f99 in main /g/g0/dahn/workspace/Flux/flux-core/src/common/libutil/test/coproc.c:138:5
    #7 0x2aaaabecdd5c in __libc_start_main /usr/src/debug/glibc-2.12-2-gc4ccff1/csu/libc-start.c:226
    #8 0x4b662c in _start (/g/g0/dahn/workspace/Flux/flux-core/src/common/libutil/test_coproc.t+0x4b662c)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /collab/usr/global/tools/clang/chaos_5_x86_64_ib/clang-omp-3.5.0/src/llvm-3.5.0.src/projects/compiler-rt/lib/asan/asan_allocator2.cc:157 __asan::AsanChunk::UsedSize(bool)
==132562==ABORTING
```
