### ISSUE TITLE
broker hang with tcmalloc build

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#958]
The broker seems to get intermittently stuck loading modules when built `--with-tcmalloc`.

For example this test hangs
```
flux start --size=2 flux comms info 
```

Attaching with gdb, one of the brokers is in the reactor loop and seems to be functioning normally.  The other is stuck in `tc_malloc()` while attempting to load the `connector-local` module via the "built in" module path:
```
gdb -p 41298 .libs/lt-flux-broker
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from .libs/lt-flux-broker...done.
Attaching to program: /home/garlick/proj/flux-core/src/broker/.libs/lt-flux-broker, process 41298
[New LWP 41328]
[New LWP 41329]
[New LWP 41330]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f998a42f159 in base::internal::SpinLockDelay(int volatile*, int, int) ()
   from /usr/lib/libtcmalloc.so.4
(gdb) bt
#0  0x00007f998a42f159 in base::internal::SpinLockDelay(int volatile*, int, int) () from /usr/lib/libtcmalloc.so.4
#1  0x00007f998a42f026 in SpinLock::SlowLock() ()
   from /usr/lib/libtcmalloc.so.4
#2  0x00007f998a41fe38 in tcmalloc::CentralFreeList::Populate() ()
   from /usr/lib/libtcmalloc.so.4
#3  0x00007f998a41ff28 in tcmalloc::CentralFreeList::FetchFromOneSpansSafe(int, void**, void**) () from /usr/lib/libtcmalloc.so.4
#4  0x00007f998a41ffbf in tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) () from /usr/lib/libtcmalloc.so.4
#5  0x00007f998a422faa in tcmalloc::ThreadCache::FetchFromCentralCache(unsigned long, unsigned long) () from /usr/lib/libtcmalloc.so.4
#6  0x00007f998a431b3b in tc_malloc () from /usr/lib/libtcmalloc.so.4
#7  0x00007f998b5ec567 in _dl_map_object_deps (map=map@entry=0x1e5e500, 
    preloads=preloads@entry=0x0, npreloads=npreloads@entry=0, 
    trace_mode=trace_mode@entry=0, open_mode=open_mode@entry=-2147483640)
    at dl-deps.c:499
#8  0x00007f998b5f3412 in dl_open_worker (a=a@entry=0x7ffc6c172d90)
    at dl-open.c:280
#9  0x00007f998b5ee394 in _dl_catch_error (
    objname=objname@entry=0x7ffc6c172d80, 
    errstring=errstring@entry=0x7ffc6c172d88, 
    mallocedp=mallocedp@entry=0x7ffc6c172d7f, 
    operate=operate@entry=0x7f998b5f3300 <dl_open_worker>, 
    args=args@entry=0x7ffc6c172d90) at dl-error.c:187
#10 0x00007f998b5f2bd9 in _dl_open (
    file=0x7ffc6c1731f0 "/home/garlick/proj/flux-core/src/modules/live/.libs/live.so", mode=-2147483639, caller_dlopen=0x7f998b39bbfb <flux_modname+27>, 
    nsid=-2, argc=<optimized out>, argv=<optimized out>, env=0x7ffc6c176a48)
    at dl-open.c:660
#11 0x00007f998a670f09 in dlopen_doit (a=a@entry=0x7ffc6c172fc0) at dlopen.c:66
#12 0x00007f998b5ee394 in _dl_catch_error (objname=0x1e19770, 
    errstring=0x1e19778, mallocedp=0x1e19768, 
    operate=0x7f998a670eb0 <dlopen_doit>, args=0x7ffc6c172fc0)
    at dl-error.c:187
#13 0x00007f998a671571 in _dlerror_run (
    operate=operate@entry=0x7f998a670eb0 <dlopen_doit>, 
    args=args@entry=0x7ffc6c172fc0) at dlerror.c:163
#14 0x00007f998a670fa1 in __dlopen (
    file=file@entry=0x7ffc6c1731f0 "/home/garlick/proj/flux-core/src/modules/live/.libs/live.so", mode=mode@entry=9) at dlopen.c:87
#15 0x00007f998b39bbfb in flux_modname (
    path=0x7ffc6c1731f0 "/home/garlick/proj/flux-core/src/modules/live/.libs/live.so") at module.c:264
#16 0x00007f998b39bde0 in flux_modname_cmp (name=0x1e147d0 "connector-local", 
    path=0x7ffc6c1731f0 "/home/garlick/proj/flux-core/src/modules/live/.libs/live.so") at module.c:282
#17 modfind (
    dirpath=dirpath@entry=0x7ffc6c174420 "/home/garlick/proj/flux-core/src/modules/live/.libs", modname=modname@entry=0x1e147d0 "connector-local")
    at module.c:324
#18 0x00007f998b39bea4 in modfind (
    dirpath=dirpath@entry=0x7ffc6c175650 "/home/garlick/proj/flux-core/src/modules/live", modname=modname@entry=0x1e147d0 "connector-local") at module.c:322
#19 0x00007f998b39bea4 in modfind (
    dirpath=0x1e1e760 "/home/garlick/proj/flux-core/src/modules", 
    modname=modname@entry=0x1e147d0 "connector-local") at module.c:322
#20 0x00007f998b39bf82 in flux_modfind (searchpath=<optimized out>, 
    modname=modname@entry=0x1e147d0 "connector-local") at module.c:343
#21 0x0000000000407e05 in load_modules (default_modules=<optimized out>, 
    ctx=0x7ffc6c176740) at broker.c:1391
#22 main (argc=<optimized out>, argv=<optimized out>) at broker.c:641

```

**Comment by garlick** [comment]
Old issue.
